import type { MaterialUnidade } from '../../tipos';

export const material: MaterialUnidade = {
  id: 'cg01-u4-classes-palavras',
  disciplina: 'CG01',
  unidade: 4,
  titulo: 'Classes de palavras',
  objetivo: 'Reconhecer e empregar as principais classes de palavras previstas no programa, analisando sua forma, função e sentido em contexto, com atenção especial ao sistema verbal, aos pronomes e à colocação pronominal na escrita formal.',
  topicosCobertos: [
    'Substantivo',
    'Adjetivo',
    'Verbo',
    'Advérbio',
    'Pronome',
    'Colocação pronominal',
    'Preposição',
    'Conjunção',
    'Interjeição',
  ],
  blocos: [
    {
      tipo: 'texto',
      titulo: '1. Classe de palavra não se identifica por uma única pergunta',
      paragrafos: [
        'As classes de palavras agrupam unidades que compartilham propriedades morfológicas, sintáticas e semânticas. Definições escolares como “substantivo é nome” ou “adjetivo é qualidade” ajudam como ponto de partida, mas são insuficientes para análise rigorosa. A classe de uma palavra deve ser reconhecida pelo conjunto de comportamentos que ela apresenta em contexto.',
        'Uma mesma forma pode desempenhar classes diferentes conforme o enunciado. Em “um homem velho”, “velho” funciona como adjetivo; em “o velho chegou”, a forma funciona substantivamente. Em “o jantar começou cedo”, “jantar” é substantivo; em “vamos jantar”, é verbo. Por isso, classificação exige observar a relação da palavra com as demais.',
        'A gramática normativa tradicional do português costuma apresentar dez classes, incluindo artigo e numeral. O programa oficial desta unidade seleciona nove tópicos específicos e não lista artigo e numeral; esta aula respeita esse recorte, embora essas duas classes apareçam ocasionalmente nos exemplos por integrarem a língua.',
      ],
    },
    {
      tipo: 'texto',
      titulo: '2. Substantivo',
      paragrafos: [
        'Substantivos constituem uma classe central de palavras que pode designar pessoas, seres, objetos, lugares, instituições, eventos, estados, processos e conceitos. Em “igreja”, “livro”, “esperança”, “leitura” e “reforma”, encontramos substantivos apesar de os referentes pertencerem a categorias semânticas muito diferentes.',
        'Morfologicamente, muitos substantivos variam em número e alguns apresentam oposição de gênero. Sintaticamente, podem ocupar o núcleo de grupos nominais e combinar-se com artigos, pronomes, numerais, adjetivos e outras expressões modificadoras: “os dois textos antigos”, “esta importante decisão”.',
        'Classificações como próprio/comum, concreto/abstrato, simples/composto e primitivo/derivado descrevem aspectos diferentes. Não devem ser confundidas com a identificação da classe: “justificação” continua sendo substantivo independentemente de ser derivado e abstrato.',
      ],
    },
    {
      tipo: 'exemplo',
      titulo: 'Substantivação em contexto',
      enunciado: 'Compare “O povo respondeu rápido” e “A resposta do povo foi rápida”.',
      explicacao: 'No primeiro enunciado, “respondeu” expressa o processo verbalmente. No segundo, “resposta” apresenta conteúdo relacionado como substantivo. Textos acadêmicos usam muitas nominalizações, como “analisar → análise” e “interpretar → interpretação”. Elas condensam ideias, mas o excesso pode tornar a prosa abstrata e pesada.',
    },
    {
      tipo: 'texto',
      titulo: '3. Adjetivo',
      paragrafos: [
        'Adjetivos caracterizam ou classificam referentes expressos por substantivos e participam de relações de concordância. Em “texto claro”, “questões históricas” e “tradição reformada”, os adjetivos delimitam ou atribuem propriedades aos substantivos.',
        'A posição pode influenciar o sentido. “Um grande homem” e “um homem grande” não são necessariamente equivalentes: no primeiro caso, “grande” tende a ter leitura avaliativa; no segundo, pode indicar dimensão física. A interpretação depende do contexto, e a liberdade de posição dos adjetivos em português não significa ausência de efeitos semânticos.',
        'Locuções adjetivas são grupos de palavras com função semelhante à de adjetivo, como “estudo da Bíblia” em certos contextos. Nem toda locução possui um adjetivo equivalente perfeito; substituir mecanicamente uma expressão por uma palavra pode alterar o sentido.',
      ],
    },
    {
      tipo: 'atividade',
      id: 'cg01-u4-a1',
      titulo: 'Atividade 1 — substantivo e adjetivo em contexto',
      enunciado: 'Analise: “A jovem pesquisadora apresentou uma pesquisa jovem e ousada”. Classifique as ocorrências de “jovem” e explique sua função em cada posição.',
      resposta: 'Na expressão “a jovem pesquisadora”, “jovem” modifica o substantivo “pesquisadora” e funciona como adjetivo. Em “uma pesquisa jovem e ousada”, também funciona como adjetivo, agora com sentido figurado relacionado a novidade, renovação ou pouca maturação. A classe permanece, mas o sentido depende do substantivo modificado e do contexto.',
    },
    {
      tipo: 'texto',
      titulo: '4. Verbo',
      paragrafos: [
        'Verbos formam uma classe flexionalmente rica no português. Podem expressar ações, processos, estados, acontecimentos e relações. Sua forma pode marcar pessoa, número, tempo e modo, além de combinar-se com formas nominais como infinitivo, gerúndio e particípio.',
        'Tempo verbal localiza ou relaciona situações temporalmente; modo expressa maneiras de apresentar o conteúdo, como fato, hipótese, desejo, ordem ou possibilidade; pessoa e número relacionam o verbo aos participantes do discurso. Em “estudaremos”, uma única forma reúne o radical lexical e marcas que situam o evento no futuro e o associam à primeira pessoa do plural.',
        'Verbos também organizam a estrutura da oração ao selecionar complementos. “Analisar” costuma pedir algo analisado; “confiar” pode introduzir complemento por preposição; “ser” participa de predicações nominais. Esse tema será aprofundado em Português 2, mas já é importante perceber que a escolha verbal afeta a arquitetura da frase.',
      ],
    },
    {
      tipo: 'quadro',
      titulo: 'Aspectos verbais essenciais para revisão',
      itens: [
        'Pessoa e número: eu estudo, nós estudamos, eles estudam.',
        'Tempo: relações de presente, passado e futuro, com valores que dependem do contexto.',
        'Modo: indicativo, subjuntivo e imperativo na classificação tradicional.',
        'Formas nominais: infinitivo, gerúndio e particípio.',
        'Locuções verbais: mais de uma forma verbal funcionando em conjunto, como “pode ocorrer” e “foi escrito”.',
      ],
    },
    {
      tipo: 'exemplo',
      titulo: 'Tempo gramatical e valor discursivo',
      enunciado: '“Amanhã eu viajo para Recife.”',
      explicacao: 'A forma verbal “viajo” é morfologicamente presente, mas o advérbio “amanhã” e o contexto atribuem valor futuro ao enunciado. Isso mostra que interpretação temporal não depende apenas da terminação verbal: morfologia, léxico e contexto cooperam.',
    },
    {
      tipo: 'texto',
      titulo: '5. Advérbio',
      paragrafos: [
        'Advérbios são palavras invariáveis em sua forma típica e modificam verbos, adjetivos, outros advérbios ou até o enunciado inteiro. Podem expressar circunstâncias e avaliações como tempo, lugar, modo, intensidade, negação, afirmação, dúvida ou perspectiva do falante.',
        'Em “leu cuidadosamente”, o advérbio modifica o verbo; em “muito importante”, modifica o adjetivo; em “bem longe”, modifica outro advérbio. Em “Provavelmente, a reunião terminará cedo”, “provavelmente” funciona sobre a proposição inteira e sinaliza o grau de compromisso do falante com a afirmação.',
        'Nem toda expressão adverbial é uma única palavra. Locuções como “com cuidado”, “à tarde”, “de fato” e “em breve” podem desempenhar funções adverbiais. A análise deve considerar o comportamento da expressão no enunciado.',
      ],
    },
    {
      tipo: 'texto',
      titulo: '6. Pronome',
      paragrafos: [
        'Pronomes participam da referência e da organização do discurso. Podem apontar para participantes da comunicação, retomar ou antecipar elementos do texto, indicar posse, localização discursiva, quantidade indefinida ou interrogação. A classe inclui diferentes subclasses com comportamentos próprios.',
        'Pronomes pessoais distinguem participantes como eu, tu, ele/ela, nós e formas correspondentes em diferentes funções. Demonstrativos como este, esse e aquele organizam referências espaciais, temporais ou textuais; possessivos indicam relações de posse ou associação; relativos como que, o qual e cujo conectam estruturas e retomam antecedentes.',
        'Em textos acadêmicos, o pronome deve possuir referente recuperável. Frases como “isso demonstra o problema” são fracas quando não está claro a que “isso” se refere. A coesão melhora quando o autor controla as cadeias referenciais e evita ambiguidades.',
      ],
    },
    {
      tipo: 'quadro',
      titulo: 'Pronomes pessoais átonos',
      itens: [
        'me, te, se, o, a, lhe, nos, vos, os, as, lhes são formas tradicionalmente tratadas como pronomes pessoais oblíquos átonos.',
        'Por serem átonos, apoiam-se fonologicamente em um verbo e sua posição é regulada por padrões de colocação pronominal.',
        'Na escrita formal brasileira, próclise, ênclise e casos específicos de mesóclise são tratados pela norma; a fala brasileira apresenta padrões próprios que nem sempre coincidem com as prescrições tradicionais.',
      ],
    },
    {
      tipo: 'texto',
      titulo: '7. Colocação pronominal',
      paragrafos: [
        'Colocação pronominal trata da posição dos pronomes átonos em relação ao verbo. Próclise ocorre quando o pronome aparece antes do verbo: “não se sabe”. Ênclise, depois do verbo: “levantou-se”. Mesóclise, no interior de certas formas futuras: “dir-se-á”. A escrita brasileira contemporânea usa a mesóclise raramente, sobretudo em registros muito formais.',
        'Na norma escrita tradicional, certos elementos favorecem ou exigem próclise, como palavras negativas, determinados pronomes e advérbios e estruturas subordinadas: “nunca me disseram”, “quem lhe contou?”, “quando se iniciou a reunião”. A ênclise é produtiva em contextos como início formal de oração: “Informou-se o resultado”, embora muitos usos da fala brasileira prefiram próclise mesmo aí.',
        'A competência importante não consiste em aplicar uma lista de “palavras atrativas” sem entender o texto. É preciso reconhecer o pronome, o verbo a que se liga e o registro. Na escrita acadêmica e oficial, convém dominar as convenções normativas; ao analisar fala espontânea, não se deve confundir diferença de padrão com ausência de gramática.',
      ],
    },
    {
      tipo: 'exemplo',
      titulo: 'Próclise e negação',
      enunciado: '“Não me enviaram o documento.”',
      explicacao: 'O pronome átono “me” aparece antes do verbo. A palavra negativa “não” cria contexto de próclise na norma escrita. A construção “Não enviaram-me o documento” contraria esse padrão normativo.',
    },
    {
      tipo: 'atividade',
      id: 'cg01-u4-a2',
      titulo: 'Atividade 2 — colocação pronominal',
      enunciado: 'Reescreva segundo a norma escrita formal e explique: (a) “Nunca disseram-me a razão”; (b) “Quem contou-lhe isso?”; (c) “Entregaram-me os documentos ontem”.',
      resposta: 'As formas esperadas são “Nunca me disseram a razão” e “Quem lhe contou isso?”, pois “nunca” e o pronome interrogativo “quem” estabelecem contextos de próclise. “Entregaram-me os documentos ontem” é compatível com a ênclise na norma formal. Em usos coloquiais brasileiros, outras posições são frequentes; a atividade trabalha especificamente a convenção formal.',
    },
    {
      tipo: 'texto',
      titulo: '8. Preposição',
      paragrafos: [
        'Preposições são palavras invariáveis que estabelecem relações entre termos, introduzindo complementos e adjuntos. Formas como a, de, em, com, por, para, sem, sob e sobre participam de relações de origem, destino, posse, matéria, localização, instrumento, causa e muitas outras, determinadas pelo contexto.',
        'O sentido não pertence isoladamente à preposição. Em “livro de história”, “mesa de madeira” e “carta de Paulo”, a mesma preposição “de” participa de relações diferentes. Verbos e nomes também podem selecionar determinadas preposições, fenômeno que se torna central no estudo de regência em Português 2.',
        'Locuções prepositivas são grupos que desempenham função semelhante, como “por causa de”, “a respeito de”, “em vez de” e “de acordo com”. Em textos formais, a escolha precisa dessas relações evita ambiguidades.',
      ],
    },
    {
      tipo: 'texto',
      titulo: '9. Conjunção',
      paragrafos: [
        'Conjunções conectam palavras, grupos ou orações e ajudam a explicitar relações lógicas e discursivas. Na classificação tradicional, conjunções coordenativas ligam estruturas com maior independência sintática, enquanto subordinativas introduzem orações dependentes dentro de uma estrutura maior.',
        'Mais importante que decorar nomes é compreender relações. “Mas” pode introduzir contraste; “porque”, causa ou explicação conforme o contexto; “portanto”, conclusão; “embora”, concessão; “se”, condição; “quando”, relação temporal. A escolha inadequada de um conectivo pode alterar o argumento inteiro.',
        'Conjunções e locuções conjuntivas são ferramentas decisivas da escrita acadêmica. Um texto não se torna coeso apenas por inserir conectivos; é preciso que a relação expressa pelo conectivo corresponda à relação real entre as ideias.',
      ],
    },
    {
      tipo: 'exemplo',
      titulo: 'A conjunção muda o argumento',
      enunciado: 'Compare: “O texto é breve, mas complexo”; “O texto é breve e complexo”; “Embora o texto seja breve, é complexo”.',
      explicacao: 'As três construções relacionam as mesmas propriedades, mas de modos diferentes. “Mas” sinaliza contraste; “e” apenas coordena; “embora” organiza a brevidade como circunstância concessiva. A gramática participa diretamente da construção do raciocínio.',
    },
    {
      tipo: 'texto',
      titulo: '10. Interjeição',
      paragrafos: [
        'Interjeições são formas ou expressões associadas a reações, chamamentos, avaliações e estados afetivos, frequentemente com forte dependência da entonação e da situação. “Ah!”, “ei!”, “ufa!”, “puxa!” e “alô!” ilustram usos comuns.',
        'Seu valor não pode ser determinado apenas por dicionário. “Ah” pode sinalizar surpresa, compreensão, decepção ou ironia conforme entonação e contexto. Interjeições mostram de maneira clara que significado linguístico inclui dimensões pragmáticas e interacionais.',
        'Na escrita formal acadêmica, interjeições são raras; em diálogos, narrativas, mensagens e transcrições, podem ser relevantes para representar a interação. A adequação ao gênero volta a ser o critério central.',
      ],
    },
    {
      tipo: 'atividade',
      id: 'cg01-u4-a3',
      titulo: 'Atividade 3 — análise integrada das classes',
      enunciado: 'Analise a frase: “Quando o jovem professor explicou cuidadosamente a questão, ninguém lhe fez perguntas difíceis, mas alguns anotaram tudo.” Identifique ao menos um substantivo, um adjetivo, um verbo, um advérbio, um pronome, uma preposição e uma conjunção e explique sua função no contexto.',
      resposta: 'Exemplos: substantivos “professor”, “questão”, “perguntas”; adjetivos “jovem”, “difíceis”; verbos “explicou”, “fez”, “anotaram”; advérbio “cuidadosamente”; pronomes “ninguém”, “lhe”, “alguns”, “tudo” conforme classificação tradicional; preposição “a” em “a questão” não é preposição neste caso, mas artigo — portanto o estudante deve procurar uma preposição verdadeira em outra formulação ou reconhecer que a frase, tal como escrita, não oferece exemplo inequívoco de todas as classes solicitadas. Conjunções “quando” e “mas”. A observação sobre a ausência de preposição é intencional: classificar exige analisar, não forçar uma resposta.',
    },
    {
      tipo: 'atividade',
      id: 'cg01-u4-a4',
      titulo: 'Atividade 4 — completar a análise com preposição',
      enunciado: 'Reescreva a frase da atividade anterior acrescentando uma expressão preposicionada sem alterar seu sentido central e identifique a relação introduzida pela preposição.',
      resposta: 'Exemplo: “Quando o jovem professor explicou cuidadosamente a questão para a turma, ninguém lhe fez perguntas difíceis, mas alguns anotaram tudo.” A preposição “para” introduz a expressão “para a turma”, indicando o destinatário da explicação. Outras reescritas são possíveis desde que a relação seja justificada.',
    },
    {
      tipo: 'texto',
      titulo: '11. Forma, função e sentido devem ser analisados juntos',
      paragrafos: [
        'A classificação morfológica não é um fim isolado. Em leitura, ela ajuda a perceber como um autor constrói referências, ações, qualificações, relações e encadeamentos. Em escrita, ajuda a revisar ambiguidades, concordância, repetição, conectivos e escolhas vocabulares.',
        'Para classificar uma palavra, use três pistas: sua forma e possibilidades de flexão; sua posição e relações sintáticas; e o sentido que constrói naquele enunciado. Nenhuma dessas pistas, sozinha, resolve todos os casos. Essa atitude analítica prepara o estudo de sintaxe em Português 2.',
      ],
    },
    {
      tipo: 'quadro',
      titulo: 'Síntese da unidade',
      itens: [
        'Substantivos nucleiam grupos nominais e podem nomear entidades, eventos, estados e conceitos.',
        'Adjetivos modificam ou classificam referentes e podem mudar de interpretação conforme posição e contexto.',
        'Verbos flexionam-se e organizam processos, estados e relações na oração.',
        'Advérbios modificam diferentes constituintes e podem atuar sobre o enunciado inteiro.',
        'Pronomes organizam referência e coesão; pronomes átonos participam das regras de colocação.',
        'Próclise, ênclise e mesóclise descrevem posições do pronome átono em relação ao verbo; a escrita formal possui convenções específicas.',
        'Preposições introduzem relações entre termos; conjunções explicitam relações entre estruturas e ideias.',
        'Interjeições dependem fortemente de situação e entonação.',
        'Classe gramatical deve ser identificada em contexto, pela combinação entre forma, função e sentido.',
      ],
    },
  ],
  fontes: [
    {
      id: 'cecierj-portugues-modulo-1',
      autor: 'Agostinho Dias Carneiro; Diogo Pinheiro; Luciano Carvalho do Nascimento',
      ano: '2016',
      titulo: 'Língua Portuguesa — Módulo 1',
      publicacao: 'Canal CECIERJ',
      url: 'https://canal.cecierj.edu.br/recurso/15402',
      idioma: 'pt',
      tipo: 'curso',
      acesso: 'livre',
      nota: 'Material didático aberto utilizado como apoio à revisão de classes de palavras, pronomes, verbos e funções linguísticas.',
    },
    {
      id: 'cecierj-portugues-iv-morfologia',
      autor: 'Ronaldo Amorim Lima et al.',
      ano: '2015',
      titulo: 'Português IV — Vol. 1',
      publicacao: 'Canal CECIERJ / Consórcio CEDERJ',
      url: 'https://canal.cecierj.edu.br/recurso/13787',
      idioma: 'pt',
      tipo: 'curso',
      acesso: 'livre',
      nota: 'Caderno universitário aberto utilizado como apoio à análise morfológica, flexão e classes de palavras.',
    },
  ],
  atualizadoEm: '2026-09-02',
};
