import type { ObraLivre } from './biblioteca';

/** Fontes abertas diretamente ligadas ao aprofundamento de História da Igreja 4. */
export const bibliotecaHistoriaModerna: ObraLivre[] = [
  {
    id: 'wesley-works-v1',
    autor: 'John Wesley',
    ano: '1771',
    titulo: 'The Works of the Rev. John Wesley, vol. I',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/59743',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04'],
    nota: 'Primeiro volume da coleção de Wesley, com sermões que permitem observar diretamente a teologia prática do avivamento metodista, em vez de depender apenas de descrições posteriores do movimento.',
    base: 'domínio público',
  },
  {
    id: 'fox-autobiography',
    autor: 'George Fox',
    ano: '1694',
    titulo: 'George Fox: An Autobiography',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/43031',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04'],
    nota: 'Fonte primária para o surgimento dos quacres, sua ênfase na experiência religiosa interior e seu conflito com estruturas e práticas eclesiásticas estabelecidas.',
    base: 'domínio público',
  },
  {
    id: 'bonar-mcheyne',
    autor: 'Andrew A. Bonar',
    ano: '1844',
    titulo: "The Biography of Robert Murray M'Cheyne",
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/15251',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04'],
    nota: 'Biografia clássica produzida por um contemporâneo e amigo de M’Cheyne. É fonte aberta para o despertamento escocês, espiritualidade presbiteriana e missões no século XIX.',
    base: 'domínio público',
  },
  {
    id: 'livingstone-missionary-travels',
    autor: 'David Livingstone',
    ano: '1857',
    titulo: 'Missionary Travels and Researches in South Africa',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/1039',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP08'],
    nota: 'Relato primário de Livingstone sobre missão, exploração, escravidão e sociedades africanas. Deve ser lido criticamente como testemunho missionário do século XIX, não como descrição neutra de povos africanos.',
    base: 'domínio público',
  },
  {
    id: 'hudson-taylor-retrospect',
    autor: 'James Hudson Taylor',
    ano: '1894',
    titulo: 'A Retrospect',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/26744',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP08'],
    nota: 'Memória autobiográfica do fundador da China Inland Mission, útil para estudar estratégia missionária, interiorização da missão na China, oração, financiamento e adaptação cultural a partir da voz do próprio movimento.',
    base: 'domínio público',
  },
  {
    id: 'paton-autobiography',
    autor: 'John G. Paton',
    ano: '1889',
    titulo: 'John G. Paton, Missionary to the New Hebrides, vol. I',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/71542',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP08'],
    nota: 'Autobiografia missionária em domínio público usada para o cristianismo nas ilhas do Pacífico. O texto preserva também pressupostos culturais do século XIX, que devem ser reconhecidos criticamente na leitura histórica.',
    base: 'domínio público',
  },
  {
    id: 'book-of-mormon-pg',
    autor: 'Joseph Smith Jr.; Church of Jesus Christ of Latter-day Saints',
    ano: '1830',
    titulo: 'The Book of Mormon',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/17',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP56'],
    nota: 'Texto primário do movimento dos Santos dos Últimos Dias. É usado para descrever historicamente suas reivindicações e doutrinas a partir de uma fonte do próprio movimento, sem atribuir autoridade canônica cristã ao documento.',
    base: 'domínio público',
  },
  {
    id: 'white-great-controversy-pg',
    autor: 'Ellen G. White',
    ano: '1888',
    titulo: 'The Great Controversy Between Christ and Satan',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/25833',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP56'],
    nota: 'Fonte primária adventista para escatologia, interpretação da história cristã, sábado e identidade denominacional. Serve ao estudo histórico do movimento, não como norma doutrinária do portal.',
    base: 'domínio público',
  },
  {
    id: 'eddy-science-health-pg',
    autor: 'Mary Baker Eddy',
    ano: '1875',
    titulo: 'Science and Health, with Key to the Scriptures',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/3458',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP56'],
    nota: 'Texto fundacional da Ciência Cristã, usado para caracterizar diretamente sua compreensão de Deus, matéria, enfermidade, cura e interpretação bíblica.',
    base: 'domínio público',
  },
];
