import type { ObraLivre } from './biblioteca';

/** Recursos educacionais abertos para aquisição e estudo de línguas. */
export const bibliotecaLinguas: ObraLivre[] = [
  {
    id: 'cecierj-linguagem-variacao',
    autor: 'Fundação CECIERJ',
    ano: '2016',
    titulo: 'Linguagem, cultura e variação linguística',
    publicacao: 'Canal CECIERJ',
    url: 'https://canal.cecierj.edu.br/recurso/16000',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Recurso educacional aberto sobre linguagem como prática social, diversidade linguística e adequação dos usos a diferentes situações de interação. Serve especialmente à unidade inicial de Português 1.',
    base: 'edição autorizada',
  },
  {
    id: 'uab-fonetica-fonologia-morfologia',
    autor: 'Marli Hermenegilda Pereira; Mikaela Roberto; Ricardo Stavola Cavaliere',
    ano: '2015',
    titulo: 'Português V — Vol. 1',
    publicacao: 'Canal CECIERJ / Consórcio CEDERJ',
    url: 'https://canal.cecierj.edu.br/recurso/17163',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Caderno didático universitário aberto de Fonética do português. O identificador interno legado foi preservado para não quebrar referências avaliativas já publicadas.',
    base: 'edição autorizada',
  },
  {
    id: 'cecierj-portugues-iv-morfologia',
    autor: 'Ronaldo Amorim Lima et al.',
    ano: '2015',
    titulo: 'Português IV — Vol. 1',
    publicacao: 'Canal CECIERJ / Consórcio CEDERJ',
    url: 'https://canal.cecierj.edu.br/recurso/13787',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Caderno didático universitário aberto com tratamento de morfologia, flexão e estrutura das palavras, útil às unidades 3 e 4 de Português 1.',
    base: 'edição autorizada',
  },
  {
    id: 'cecierj-portugues-modulo-1',
    autor: 'Agostinho Dias Carneiro; Diogo Pinheiro; Luciano Carvalho do Nascimento',
    ano: '2016',
    titulo: 'Língua Portuguesa — Módulo 1',
    publicacao: 'Canal CECIERJ',
    url: 'https://canal.cecierj.edu.br/recurso/15402',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Material didático aberto que percorre classes de palavras, pronome, verbo e funções da linguagem, servindo como apoio à revisão morfológica de Português 1.',
    base: 'edição autorizada',
  },
  {
    id: 'ewald-elementary-greek-2022',
    autor: 'Owen Ewald',
    ano: '2022',
    titulo: 'Elementary New Testament Greek',
    publicacao: 'Seattle Pacific University Library — Faculty Open Access Books',
    url: 'https://digitalcommons.spu.edu/open_books/2/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE08', 'TE09', 'TE10'],
    nota: 'Livro-texto universitário aberto de grego do Novo Testamento, com explicações, vocabulário, leituras e exercícios cumulativos. Distribuído sob licença CC BY-NC-SA 4.0 e especialmente adequado para aquisição progressiva da língua.',
    base: 'edição autorizada',
  },
  {
    id: 'machen-greek-1923',
    autor: 'J. Gresham Machen',
    ano: '1923',
    titulo: 'New Testament Greek for Beginners',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/m/machen/greek/home.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE08', 'TE09', 'TE10'],
    nota: 'Gramática introdutória clássica em domínio público, com paradigmas, vocabulário e exercícios. Serve como contraponto histórico e material adicional de prática ao recurso aberto contemporâneo.',
    base: 'domínio público',
  },
];
