import type { Idioma, NivelAcesso } from '../tipos';

/**
 * Obras de referência disponíveis legalmente sem custo.
 *
 * Critério de entrada, deliberadamente estreito: domínio público, edição
 * digital autorizada pelo detentor dos direitos, ou empréstimo digital
 * controlado de biblioteca. Cópia não autorizada de obra em catálogo NÃO
 * entra — nem por conveniência. Além de ser errado com quem publica em
 * português, esses links morrem, e um portal de estudo não pode ser
 * construído sobre eles.
 *
 * Quando a obra de referência ainda está em catálogo, a resposta do portal
 * não é indicar uma cópia pirata: é ensinar a doutrina no próprio verbete,
 * com o aparato primário aberto listado aqui.
 */
export interface ObraLivre {
  id: string;
  autor: string;
  ano: string;
  titulo: string;
  publicacao: string;
  url: string;
  idioma: Idioma;
  acesso: NivelAcesso;
  /** Códigos de disciplina que esta obra serve. */
  disciplinas: string[];
  /** Por que vale a pena, e o que ela substitui. */
  nota: string;
  /** Por que é lícito estar aqui. */
  base: 'domínio público' | 'edição autorizada' | 'empréstimo de biblioteca';
}

export const biblioteca: ObraLivre[] = [
  {
    id: 'calvino-institutas',
    autor: 'João Calvino',
    ano: '1559',
    titulo: 'Institutes of the Christian Religion (trad. Beveridge)',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/calvin/institutes.all.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07', 'TS11', 'TS12'],
    nota: 'A obra fundadora da dogmática reformada, em texto integral. Percorre praticamente todo o programa de Teologia Sistemática dos quatro anos. Se você só puder ler uma obra primária, leia esta.',
    base: 'domínio público',
  },
  {
    id: 'calvino-institutas-pdf',
    autor: 'João Calvino',
    ano: '1559',
    titulo: 'The Institutes of the Christian Religion — PDF integral',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/calvin/institutes/formats/institutes.pdf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07'],
    nota: 'Mesma tradução em arquivo único, para leitura offline e citação por página.',
    base: 'domínio público',
  },
  {
    id: 'calvino-romanos',
    autor: 'João Calvino',
    ano: '1540',
    titulo: 'Commentary on Romans',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/calvin/calcom38.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE12', 'TE13', 'TE20', 'TE21', 'TS04'],
    nota: 'O primeiro comentário de Calvino e o manifesto do método exegético reformado. A epístola dedicatória é leitura obrigatória em Hermenêutica.',
    base: 'domínio público',
  },
  {
    id: 'hodge-st1',
    autor: 'Charles Hodge',
    ano: '1872',
    titulo: 'Systematic Theology — vol. I: Teologia',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/hodge/theology1.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01'],
    nota: 'Prolegômenos, Bibliologia e Teontologia em exposição completa. Cobre integralmente o programa de TS01 e é a matriz de Princeton por trás de boa parte dos manuais em português.',
    base: 'domínio público',
  },
  {
    id: 'hodge-st2',
    autor: 'Charles Hodge',
    ano: '1872',
    titulo: 'Systematic Theology — vol. II: Antropologia',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/hodge/theology2.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS02', 'TS03'],
    nota: 'Criação, imagem de Deus, pacto das obras, queda, pecado original e livre-arbítrio: o programa de TS02 inteiro.',
    base: 'domínio público',
  },
  {
    id: 'hodge-st3-pdf',
    autor: 'Charles Hodge',
    ano: '1873',
    titulo: 'Systematic Theology — vol. III: Soteriologia e Escatologia (PDF)',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/h/hodge/theology3/cache/theology3.pdf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TS06', 'TS07'],
    nota: 'Vocação, regeneração, fé, justificação, santificação, meios da graça e últimas coisas.',
    base: 'domínio público',
  },
  {
    id: 'bavinck-gd1',
    autor: 'Herman Bavinck',
    ano: '1895',
    titulo: 'Gereformeerde Dogmatiek — Deel 1',
    publicacao: 'Digitale Bibliotheek voor de Nederlandse Letteren (DBNL)',
    url: 'https://www.dbnl.org/tekst/bavi002gere01_01/',
    idioma: 'nl',
    acesso: 'livre',
    disciplinas: ['TS01'],
    nota: 'O original holandês, em domínio público e texto integral. A tradução inglesa em quatro volumes custa algumas centenas de reais; o holandês de Bavinck é surpreendentemente acessível com dicionário, e este volume é a melhor exposição existente da doutrina dos princípios.',
    base: 'domínio público',
  },
  {
    id: 'bavinck-gd-obra',
    autor: 'Herman Bavinck',
    ano: '1895-1901',
    titulo: 'Gereformeerde Dogmatiek — os quatro volumes',
    publicacao: 'DBNL',
    url: 'https://www.dbnl.org/tekst/bavi002gere00_01/',
    idioma: 'nl',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07'],
    nota: 'Página da obra completa, com acesso aos quatro volumes e aos PDFs. A dogmática reformada mais equilibrada já escrita.',
    base: 'domínio público',
  },
  {
    id: 'bavinck-rd-monergism',
    autor: 'Herman Bavinck',
    ano: '1895',
    titulo: 'Reformed Dogmatics — página de acesso',
    publicacao: 'Monergism',
    url: 'https://www.monergism.com/reformed-dogmatics-ebook',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07'],
    nota: 'Para quem lê inglês com mais conforto que holandês.',
    base: 'edição autorizada',
  },
  {
    id: 'turretin-latim',
    autor: 'Francis Turretin',
    ano: '1679',
    titulo: 'Institutio Theologiae Elencticae',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/institutiotheol00turrgoog',
    idioma: 'la',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS11', 'TS53'],
    nota: 'O ápice da escolástica reformada, em latim e domínio público. É a fonte por trás das distinções técnicas que os manuais modernos repetem sem citar.',
    base: 'domínio público',
  },
  {
    id: 'turretin-ingles',
    autor: 'Francis Turretin',
    ano: '1679',
    titulo: 'Institutes of Elenctic Theology (trad. Giger)',
    publicacao: 'Internet Archive — empréstimo digital',
    url: 'https://archive.org/details/institutesofelen0001turr',
    idioma: 'en',
    acesso: 'cadastro',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04'],
    nota: 'A tradução ainda está em catálogo; o Internet Archive a empresta por tempo limitado, com conta gratuita. É empréstimo de biblioteca, não download.',
    base: 'empréstimo de biblioteca',
  },
  {
    id: 'cfw-ipib',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'Confissão de Fé de Westminster',
    publicacao: 'Igreja Presbiteriana Independente do Brasil',
    url: 'https://ipib.org.br/confissao-de-fe-de-westminster/',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53', 'TP12', 'TP13'],
    nota: 'O padrão subordinado da IPB, em português. Base direta de TS11 (Símbolos de Fé) e referência constante em toda a Sistemática.',
    base: 'domínio público',
  },
  {
    id: 'cfw-braga',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'A Confissão de Fé de Westminster — edição portuguesa',
    publicacao: 'Igreja Cristã Presbiteriana de Braga',
    url: 'https://www.icpbraga.pt/documentos/cfw',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53'],
    nota: 'Útil para cotejo de tradução: onde as duas versões divergem, quase sempre há uma decisão interpretativa por trás.',
    base: 'domínio público',
  },
  {
    id: 'cfw-ipcambe',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'Confissão de Fé de Westminster — cap. I, Da Escritura Sagrada',
    publicacao: 'Igreja Presbiteriana de Cambé (IPB)',
    url: 'https://ipcambe.ipb.org.br/boletim/confissao-de-fe-de-westminster',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS11'],
    nota: 'Hospedada em domínio da própria IPB.',
    base: 'domínio público',
  },
  {
    id: 'monergismo',
    autor: 'Vários',
    ano: '—',
    titulo: 'Monergismo — acervo de teologia reformada em português',
    publicacao: 'monergismo.com',
    url: 'https://www.monergismo.com/',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07', 'TE12', 'TH01'],
    nota: 'O maior acervo lusófono de textos reformados traduzidos e disponibilizados com autorização. Primeira parada para quem lê só em português.',
    base: 'edição autorizada',
  },
  {
    id: 'ccel',
    autor: 'Vários',
    ano: '—',
    titulo: 'Christian Classics Ethereal Library',
    publicacao: 'ccel.org',
    url: 'https://www.ccel.org/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TH01', 'TH02', 'TH03', 'TH07', 'TE12'],
    nota: 'Milhares de clássicos cristãos em domínio público, com texto navegável e PDF. Padres, medievais, reformadores e puritanos.',
    base: 'domínio público',
  },
  {
    id: 'dbnl',
    autor: 'Vários',
    ano: '—',
    titulo: 'Digitale Bibliotheek voor de Nederlandse Letteren',
    publicacao: 'dbnl.org',
    url: 'https://www.dbnl.org/',
    idioma: 'nl',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS12', 'TH04'],
    nota: 'O acervo digital das letras holandesas. Indispensável para a tradição neocalvinista — Bavinck, Kuyper e a discussão da cosmovisão em TS12.',
    base: 'domínio público',
  },
  {
    id: 'archive',
    autor: 'Vários',
    ano: '—',
    titulo: 'Internet Archive',
    publicacao: 'archive.org',
    url: 'https://archive.org/',
    idioma: 'en',
    acesso: 'parcial',
    disciplinas: ['TS01', 'TH01', 'TH05', 'TH06'],
    nota: 'Domínio público em download livre e obras em catálogo por empréstimo digital com conta gratuita. Atenção ao distinguir os dois casos.',
    base: 'empréstimo de biblioteca',
  },
  {
    id: 'schaff-hcc',
    autor: 'Philip Schaff',
    ano: '1858-1890',
    titulo: 'History of the Christian Church (8 volumes)',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/schaff/hcc2.all.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01', 'TH02', 'TH03', 'TH04', 'TH07', 'TH08'],
    nota: 'A história da Igreja padrão em língua inglesa, em domínio público. Sozinha cobre o programa dos quatro semestres de História da Igreja — substituto direto de qualquer manual em catálogo.',
    base: 'domínio público',
  },
  {
    id: 'anf',
    autor: 'Roberts e Donaldson (eds.)',
    ano: '1885',
    titulo: 'Ante-Nicene Fathers — os padres anteriores a Niceia',
    publicacao: 'CCEL',
    url: 'https://ccel.org/ccel/schaff/anf01/anf01.i.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01', 'TH07', 'TS01'],
    nota: 'As fontes primárias dos dois primeiros séculos em tradução: Clemente, Inácio, Policarpo, a Didaqué, Justino Mártir e o Contra as Heresias de Irineu.',
    base: 'domínio público',
  },
  {
    id: 'schaff-archive',
    autor: 'Philip Schaff',
    ano: '1885',
    titulo: 'History of the Christian Church, vol. II — cópia alternativa',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/historyofthechri009648mbp',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01'],
    nota: 'Alternativa ao CCEL, que recusa conexões vindas de faixas de IP de nuvem.',
    base: 'domínio público',
  },
  {
    id: 'spurgeon-lectures',
    autor: 'Charles Haddon Spurgeon',
    ano: '1877',
    titulo: 'Lectures to My Students',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/lecturestomystud1877spur',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP14', 'TP01', 'TP02', 'TP15'],
    nota: 'As palestras de Spurgeon aos alunos do Pastors College, em domínio público. Ainda hoje o tratado mais útil sobre a vida, o preparo e a entrega do pregador.',
    base: 'domínio público',
  },
  {
    id: 'spurgeon-segunda',
    autor: 'Charles Haddon Spurgeon',
    ano: '1877',
    titulo: 'Second Series of Lectures to My Students',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/secondseriesofle00spur',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP14'],
    nota: 'A segunda série trata sobretudo da voz e da entrega — o material da unidade 4 do programa de Homilética.',
    base: 'domínio público',
  },
  {
    id: 'vos-idea-bt',
    autor: 'Geerhardus Vos',
    ano: '1894',
    titulo: 'The Idea of Biblical Theology as a Science and as a Theological Discipline',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/inaugurationofrevge00prin',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE14', 'TE15', 'TE12'],
    nota: 'A aula inaugural em Princeton que fundou a teologia bíblica em bases reformadas. Curta — cabe numa tarde — e contém a distinção entre processo e produto que organiza a disciplina inteira. É o melhor ponto de entrada gratuito para TE14.',
    base: 'domínio público',
  },
  {
    id: 'vos-reino',
    autor: 'Geerhardus Vos',
    ano: '1903',
    titulo: 'The Teaching of Jesus Concerning the Kingdom of God and the Church',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/theteachingofjes00vosuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE15', 'TP07', 'TS07', 'TS06'],
    nota: 'Demonstra que o reino é presente e futuro no próprio ensino de Jesus, e que a igreja é a forma que ele assume no intervalo. É a raiz da escatologia inaugurada que os manuais caros de escatologia resumem em poucas páginas.',
    base: 'domínio público',
  },
  {
    id: 'vos-self-disclosure',
    autor: 'Geerhardus Vos',
    ano: '1926',
    titulo: 'The Self-Disclosure of Jesus',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/selfdisclosureof00vosg_0',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE15', 'TS03'],
    nota: 'Como Jesus revela a própria identidade nos evangelhos, com resposta à crítica liberal que separava o Jesus da história do Cristo da fé. Complementa o volume sobre o reino pelo lado cristológico.',
    base: 'domínio público',
  },
  {
    id: 'warfield-lord-of-glory',
    autor: 'Benjamin B. Warfield',
    ano: '1907',
    titulo: 'The Lord of Glory: os títulos de Cristo no Novo Testamento',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/lordofglorystud00warf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS03', 'TE15', 'TS51'],
    nota: 'Levantamento corpo a corpo — sinóticos, João, Paulo, Hebreus — de cada designação dada a Cristo. Serve para verificar por conta própria se a alta cristologia é acréscimo tardio ou está nos textos mais antigos, em vez de aceitar a resposta de um manual.',
    base: 'domínio público',
  },
  {
    id: 'machen-liberalismo',
    autor: 'J. Gresham Machen',
    ano: '1923',
    titulo: 'Christianity and Liberalism',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/christianitylibe00mach_0',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS11', 'TS54', 'TS51'],
    nota: 'Compara ponto a ponto — Deus, homem, Bíblia, Cristo, salvação, igreja — as duas teologias que dividiam as mesmas denominações no início do século XX. Continua sendo a exposição mais clara do que estava em jogo, e o livro é curto.',
    base: 'domínio público',
  },
  {
    id: 'edwards-avivamentos',
    autor: 'Jonathan Edwards',
    ano: '1737–1742',
    titulo: 'Edwards on Revivals: A Faithful Narrative e Thoughts on the Revival',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/edwardsonrevival00edwa',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP09', 'TS05'],
    nota: 'Um volume com o relato de 1737 e a defesa crítica de 1742 — Edwards defendendo o avivamento e submetendo-o a exame no mesmo lugar. Leitura obrigatória para quem precisa avaliar movimentos contemporâneos sem cair no entusiasmo nem no ceticismo automático.',
    base: 'domínio público',
  },
  {
    id: 'edwards-afeicoes',
    autor: 'Jonathan Edwards',
    ano: '1746',
    titulo: 'A Treatise Concerning Religious Affections',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/treatiseconcerni1746edwa',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TS05', 'TP03', 'TH04'],
    nota: 'A obra que distingue, sinal por sinal, o que não prova nada sobre uma experiência religiosa do que a caracteriza como obra do Espírito. Substitui uma prateleira inteira de literatura sobre segurança da salvação e discernimento espiritual.',
    base: 'domínio público',
  },
  {
    id: 'carey-enquiry',
    autor: 'William Carey',
    ano: '1792',
    titulo: 'An Enquiry into the Obligations of Christians to Use Means for the Conversion of the Heathens',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/pts_enquiryintotheobligations_1687_2',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP07', 'TP08', 'TH04', 'TH51'],
    nota: 'O opúsculo que abriu o período moderno das missões protestantes, com o argumento de que a comissão e a promessa que a acompanha duram o mesmo tanto — seguido das tabelas de população e religião por região. Reprodução do original de 1792.',
    base: 'domínio público',
  },
  {
    id: 'warneck-missoes',
    autor: 'Gustav Warneck',
    ano: '1901',
    titulo: 'Outline of a History of Protestant Missions from the Reformation to the Present Time',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/outlineofhistorypc00warn',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP07', 'TP08', 'TH04', 'TH51'],
    nota: 'Panorama escrito pelo autor que fundou a missiologia como disciplina acadêmica. Cobre tanto o longo período em que o protestantismo não fez missões quanto a explosão de sociedades a partir de 1792 — a matéria de TH51 inteira.',
    base: 'domínio público',
  },
  {
    id: 'baxter-reformed-pastor',
    autor: 'Richard Baxter',
    ano: '1656',
    titulo: 'The Reformed Pastor',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/reformedpastor00baxt',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP01', 'TP02', 'TP03', 'TP10'],
    nota: 'O clássico sobre o cuidado pastoral pessoa a pessoa, escrito por quem catequizava família por família em Kidderminster. É a obra que está por trás de quase todo manual moderno de teologia pastoral — e sai de graça.',
    base: 'domínio público',
  },
  {
    id: 'owen-mortification',
    autor: 'John Owen',
    ano: '1656',
    titulo: 'The Mortification of Sin in Believers',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/mortificationofs00owen',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TP03', 'TP01'],
    nota: 'O tratado puritano sobre a luta contra o pecado no crente. Trata em detalhe do que a literatura devocional atual costuma resolver em slogan, e é a referência de fundo do aconselhamento reformado.',
    base: 'domínio público',
  },
  {
    id: 'owen-death-of-death',
    autor: 'John Owen',
    ano: '1648',
    titulo: 'The Death of Death in the Death of Christ',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/deathofdeathinde00owen_0',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS03', 'TS04'],
    nota: 'A defesa clássica da expiação definida, discutindo a extensão da obra de Cristo com um rigor que nenhum resumo reproduz. Quem quer avaliar a controvérsia sobre o alcance da expiação deve ler a peça de acusação no original, e ela está aqui.',
    base: 'domínio público',
  },
  {
    id: 'ryle-holiness',
    autor: 'J. C. Ryle',
    ano: '1887',
    titulo: 'Holiness: Its Nature, Hindrances, Difficulties and Roots',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/HolinessJ.C.Ryle1887',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TP01', 'TP03'],
    nota: 'Escrito contra a ideia de que a santificação seria uma segunda bênção recebida de uma vez. Direto, pastoral e sem jargão — o livro mais acessível desta lista para quem está começando.',
    base: 'domínio público',
  },
  {
    id: 'boston-fourfold',
    autor: 'Thomas Boston',
    ano: '1720',
    titulo: 'Human Nature in Its Fourfold State',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/humannatureinits00bostuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS02', 'TS04', 'TP14'],
    nota: 'Antropologia teológica em quatro estados — inocência, corrupção, graça e glória. Cobre o programa de TS02 em forma de pregação, o que o torna útil também como modelo de como se prega doutrina.',
    base: 'domínio público',
  },
  {
    id: 'aa-hodge-outlines',
    autor: 'A. A. Hodge',
    ano: '1878',
    titulo: 'Outlines of Theology',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/outlinesoftheolo1878hodg',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07', 'TS11'],
    nota: 'Sistemática reformada completa em pergunta e resposta, bem mais curta que os três volumes do pai. É a melhor opção gratuita para quem quer um manual de consulta rápida em vez de uma obra para ler de ponta a ponta.',
    base: 'domínio público',
  },
  {
    id: 'kuyper-calvinismo',
    autor: 'Abraham Kuyper',
    ano: '1898',
    titulo: 'Calvinism: Six Lectures (Stone Lectures, Princeton)',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/calvinismsixlect00kuyp',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS12', 'TS51', 'TS54', 'CG08'],
    nota: 'As seis conferências que apresentaram o calvinismo como sistema de vida — religião, política, ciência, arte — e de onde vem quase todo o vocabulário atual de cosmovisão, inclusive a soberania nas esferas. É a fonte que os livros de cosmovisão citam.',
    base: 'domínio público',
  },
  {
    id: 'schaff-creeds-3',
    autor: 'Philip Schaff',
    ano: '1877',
    titulo: 'The Creeds of Christendom, vol. III — as confissões protestantes',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/TheCreedsOfChristendomV3',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53', 'TH03'],
    nota: 'Os textos das confissões protestantes reunidos e comparados, com o original ao lado da tradução. Permite conferir por conta própria o que Westminster, Heidelberg, Dort e a Confissão Belga de fato dizem, em vez de depender de citações de segunda mão.',
    base: 'domínio público',
  },
  {
    id: 'matthew-henry',
    autor: 'Matthew Henry',
    ano: '1710',
    titulo: 'An Exposition of the Old and New Testament (6 volumes)',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/expositionofoldn11henr',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE12', 'TE13', 'TE20', 'TE21', 'TP15', 'TP16', 'TP17', 'TP18', 'TP19'],
    nota: 'Comentário de toda a Bíblia, versículo a versículo, com aplicação. Não substitui um comentário técnico para exegese em hebraico ou grego, mas resolve a maior parte das dúvidas de sentido e é o recurso gratuito mais completo para preparação de sermão.',
    base: 'domínio público',
  },
  {
    id: 'schaff-hcc3',
    autor: 'Philip Schaff',
    ano: '1889',
    titulo: 'History of the Christian Church, vol. III — Niceia e a igreja pós-nicena',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/schaff/hcc3.all.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH02', 'TS03', 'TS01'],
    nota: 'O volume que cobre o período dos concílios — Niceia, Constantinopla, Éfeso, Calcedônia — com os documentos e o contexto político. É a matéria de TH02 em fonte primária narrada.',
    base: 'domínio público',
  },
  {
    id: 'nicea-wikisource',
    autor: 'Concílio de Niceia',
    ano: '325',
    titulo: 'O Símbolo Niceno — texto e notas',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/Nicene_and_Post-Nicene_Fathers:_Series_II/Volume_XIV/The_First_Ecumenical_Council/The_Nicene_Creed',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS03', 'TH02', 'TS53'],
    nota: 'O texto do credo com as notas históricas da coleção Nicene and Post-Nicene Fathers. Vale ler o documento em vez de a paráfrase: é curto, e a palavra que dividiu a igreja no século IV está nele.',
    base: 'domínio público',
  },
  {
    id: 'calcedonia-wikisource',
    autor: 'Concílio de Calcedônia',
    ano: '451',
    titulo: 'A Definição de Fé de Calcedônia',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/Nicene_and_Post-Nicene_Fathers:_Series_II/Volume_XIV/The_Fourth_Ecumenical_Council/The_Definition_of_Faith',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS03', 'TH02', 'TS53'],
    nota: 'A definição que fixou o vocabulário da cristologia — uma pessoa, duas naturezas, e os quatro advérbios negativos. Cabe em uma página e é a base de tudo o que os manuais de cristologia discutem depois.',
    base: 'domínio público',
  },
  {
    id: 'eusebio-he',
    autor: 'Eusébio de Cesareia',
    ano: '325',
    titulo: 'História Eclesiástica, livro III — os escritos reconhecidos e os disputados',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/Nicene_and_Post-Nicene_Fathers:_Series_II/Volume_I/Church_History_of_Eusebius/Book_III/Chapter_25',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE02', 'TE01', 'TH01'],
    nota: 'O capítulo em que Eusébio classifica os livros em reconhecidos, disputados e espúrios — a fonte antiga mais citada nas discussões sobre a formação do cânon, disponível de graça em vez de resumida num manual de introdução ao Novo Testamento.',
    base: 'domínio público',
  },
  {
    id: 'spurgeon-soul-winner',
    autor: 'Charles Haddon Spurgeon',
    ano: '1895',
    titulo: 'The Soul Winner',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/soulwinner0000chsp',
    idioma: 'en',
    acesso: 'cadastro',
    disciplinas: ['TP09', 'TP14', 'TP59'],
    nota: 'Sobre evangelização feita por um calvinista convicto, o que a torna útil justamente para quem não vê como as duas coisas se juntam. Empréstimo digital controlado: exige conta gratuita no Internet Archive.',
    base: 'empréstimo de biblioteca',
  },
  {
    id: 'ci-ipb',
    autor: 'Igreja Presbiteriana do Brasil',
    ano: '1950',
    titulo: 'Constituição da Igreja Presbiteriana do Brasil',
    publicacao: 'Comissão Executiva do Supremo Concílio da IPB',
    url: 'https://www.executivaipb.com.br/site/constituicao/constituicao.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP12', 'TP13', 'TS11'],
    nota: 'O documento que rege a IPB — governo, disciplina e liturgia. Publicado pela própria denominação. O certificado do site venceu em agosto de 2026, então o navegador pode exibir um aviso antes de abrir o PDF; o documento em si continua no ar.',
    base: 'edição autorizada',
  },
  {
    id: 'manual-presbiteriano',
    autor: 'Igreja Presbiteriana do Brasil',
    ano: '2024',
    titulo: 'Manual Presbiteriano — edição revista com notas remissivas',
    publicacao: 'Comissão Executiva do Supremo Concílio da IPB',
    url: 'https://www.executivaipb.com.br/arquivos/manual_presbiteriano_2024.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP12', 'TP13', 'TP02', 'TP06'],
    nota: 'Constituição, códigos e resoluções em vigor, com notas remissivas. É a referência de trabalho para quem exerce ofício na IPB. Mesmo aviso de certificado do documento anterior.',
    base: 'edição autorizada',
  },
  {
    id: 'sep',
    autor: 'Universidade Stanford',
    ano: '1995–',
    titulo: 'Stanford Encyclopedia of Philosophy',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09', 'CG65', 'CG58', 'TS51'],
    nota: 'Enciclopédia filosófica revisada por pares, com verbetes assinados por especialistas e bibliografia atualizada. Substitui integralmente os manuais caros de história da filosofia para consulta, e é a única obra desta lista escrita para o leitor de hoje.',
    base: 'edição autorizada',
  },
  {
    id: 'lery-pt',
    autor: 'Jean de Léry',
    ano: '1578',
    titulo: 'História de uma viagem feita à terra do Brasil',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/historiadeumavia00lery',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'TH01', 'CG11', 'CG63'],
    nota: 'Relato de testemunha ocular da colônia calvinista na Guanabara (1557), com a Confissão da Guanabara — a primeira confissão reformada das Américas — e a execução dos três que a assinaram. É também um dos primeiros registros etnográficos sobre os tupinambás. Uma das raras fontes primárias desta lista disponíveis em português.',
    base: 'domínio público',
  },
  {
    id: 'lery-fr',
    autor: 'Jean de Léry',
    ano: '1578',
    titulo: 'Histoire d’un voyage fait en la terre du Brésil — edição original',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/histoiredunvoyag01lryj',
    idioma: 'fr',
    acesso: 'livre',
    disciplinas: ['TH05'],
    nota: 'A primeira edição, de La Rochelle, para conferir passagens em que as traduções divergem — sobretudo nos capítulos sobre o rompimento com Villegagnon.',
    base: 'domínio público',
  },
  {
    id: 'simonton-sermoes',
    autor: 'Ashbel Green Simonton',
    ano: '1867',
    titulo: 'Sermões escolhidos',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/sermoesescolhido00simo',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'TH06', 'TP14'],
    nota: 'Os sermões do fundador do presbiterianismo brasileiro, em português. Permite ver em fonte primária o que ele de fato pregava, em vez de depender da imagem construída depois — e serve de amostra de homilética do século XIX no Brasil.',
    base: 'domínio público',
  },
  {
    id: 'codex-sinaiticus',
    autor: 'British Library e parceiros',
    ano: 'séc. IV',
    titulo: 'Codex Sinaiticus — manuscrito digitalizado com transcrição',
    publicacao: 'Codex Sinaiticus Project',
    url: 'https://www.codexsinaiticus.org/en/manuscript.aspx',
    idioma: 'grc',
    acesso: 'livre',
    disciplinas: ['TE52', 'TE02', 'TE08', 'TE09', 'TS01'],
    nota: 'A cópia completa mais antiga do Novo Testamento, do século IV, reunida digitalmente pelas quatro instituições que guardam suas partes. Imagem da página ao lado da transcrição palavra por palavra, com as correções de mãos posteriores marcadas. Serve também de material de leitura para quem estuda grego.',
    base: 'edição autorizada',
  },
  {
    id: 'kenyon-manuscritos',
    autor: 'Frederic G. Kenyon',
    ano: '1895',
    titulo: 'Our Bible and the Ancient Manuscripts',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/ourbibleancient00keny',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE52', 'TE01', 'TE02'],
    nota: 'Introdução clássica à transmissão do texto bíblico, escrita pelo então diretor do Museu Britânico para leigos. Anterior aos papiros do século XX, portanto desatualizada em achados, mas insuperada como explicação de como o trabalho é feito.',
    base: 'domínio público',
  },
  {
    id: 'westcott-hort',
    autor: 'B. F. Westcott e F. J. A. Hort',
    ano: '1882',
    titulo: 'The New Testament in the Original Greek: Introduction and Appendix',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/newtestamentinor82west',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE52', 'TE02'],
    nota: 'O volume que expõe o método por trás da edição de 1881 e discute as passagens em disputa. É a peça central da controvérsia sobre o texto crítico: quem quer avaliá-la deve ler o argumento original, não apenas as críticas a ele.',
    base: 'domínio público',
  },
  {
    id: 'lutero-tres-tratados',
    autor: 'Martinho Lutero',
    ano: '1520',
    titulo: 'First Principles of the Reformation: as 95 teses e os três tratados primários',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/firstprinciples00buchgoog',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03', 'TP01', 'TS11', 'TS06'],
    nota: 'Reúne À Nobreza Cristã da Nação Alemã, O Cativeiro Babilônico e A Liberdade Cristã — os três escritos de 1520 em que a Reforma expõe seu programa. Traz o argumento do sacerdócio de todos os crentes, que demoliu a divisão entre estado espiritual e temporal. A biblioteca não tinha nenhuma obra de Lutero.',
    base: 'domínio público',
  },
];

export const porDisciplina = (codigo: string) =>
  biblioteca.filter((o) => o.disciplinas.includes(codigo));
