import type { ObraLivre } from './biblioteca';

/** Recursos educacionais abertos para aquisição e estudo de línguas. */
export const bibliotecaLinguas: ObraLivre[] = [
  {
    id: 'cecierj-linguagem-variacao',
    autor: 'Fundação CECIERJ',
    ano: '2016',
    titulo: 'Linguagem, cultura e variação linguística',
    publicacao: 'Canal CECIERJ',
    url: 'https://canal.cecierj.edu.br/recurso/16000',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Recurso educacional aberto sobre linguagem como prática social, diversidade linguística e adequação dos usos a diferentes situações de interação. Serve especialmente à unidade inicial de Português 1.',
    base: 'edição autorizada',
  },
  {
    id: 'uab-fonetica-fonologia-morfologia',
    autor: 'Maria Helena Mira Mateus',
    ano: '1991',
    titulo: 'Fonética, fonologia e morfologia do português: a linguagem e as línguas',
    publicacao: 'Repositório Aberto da Universidade Aberta',
    url: 'https://repositorioaberto.uab.pt/handle/10400.2/7188',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Recurso acadêmico de acesso aberto que introduz o objeto da linguística e distingue fonética, fonologia e morfologia do português.',
    base: 'edição autorizada',
  },
  {
    id: 'cecierj-portugues-iv-morfologia',
    autor: 'Ronaldo Amorim Lima et al.',
    ano: '2015',
    titulo: 'Português IV — Vol. 1',
    publicacao: 'Canal CECIERJ / Consórcio CEDERJ',
    url: 'https://canal.cecierj.edu.br/recurso/13787',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Caderno didático universitário aberto com tratamento de morfologia, flexão e estrutura das palavras, útil às unidades 3 e 4 de Português 1.',
    base: 'edição autorizada',
  },
  {
    id: 'cecierj-portugues-modulo-1',
    autor: 'Agostinho Dias Carneiro; Diogo Pinheiro; Luciano Carvalho do Nascimento',
    ano: '2016',
    titulo: 'Língua Portuguesa — Módulo 1',
    publicacao: 'Canal CECIERJ',
    url: 'https://canal.cecierj.edu.br/recurso/15402',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG01'],
    nota: 'Material didático aberto que percorre classes de palavras, pronome, verbo e funções da linguagem, servindo como apoio à revisão morfológica de Português 1.',
    base: 'edição autorizada',
  },
];
