import type { ObraLivre } from './biblioteca';

/**
 * Fontes institucionais e documentos primários para a história da Igreja no
 * século XX. Mantidas em módulo próprio porque formam um conjunto documental
 * coerente e permitem expansão posterior sem engrossar os arquivos históricos.
 */
export const bibliotecaSeculo20: ObraLivre[] = [
  {
    id: 'barmen-ekd-1934',
    autor: 'Sínodo Confessante da Igreja Evangélica Alemã',
    ano: '1934',
    titulo: 'The Theological Declaration of Barmen',
    publicacao: 'Evangelical Church in Germany (EKD)',
    url: 'https://www.ekd.de/en/The-Barmen-Declaration-303.htm',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS11', 'CG65'],
    nota: 'Texto integral da Declaração de Barmen no portal da Igreja Evangélica na Alemanha. É a fonte primária para estudar a resposta da Igreja Confessante à captura do protestantismo pelos chamados Cristãos Alemães e ao totalitarismo nazista.',
    base: 'edição autorizada',
  },
  {
    id: 'wcc-history-1948',
    autor: 'World Council of Churches',
    ano: '1948–2026',
    titulo: 'History of the World Council of Churches',
    publicacao: 'World Council of Churches',
    url: 'https://www.oikoumene.org/about-the-wcc/history',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TH52', 'TP07'],
    nota: 'História institucional do Conselho Mundial de Igrejas, fundado em Amsterdã em 1948. Permite acompanhar o ecumenismo por sua própria autodescrição, inclusive expansão global, missão, diálogo e ação social.',
    base: 'edição autorizada',
  },
  {
    id: 'vaticano2-dei-verbum',
    autor: 'Concílio Vaticano II',
    ano: '1965',
    titulo: 'Dei Verbum — Constituição Dogmática sobre a Revelação Divina',
    publicacao: 'Santa Sé',
    url: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS01', 'TS53'],
    nota: 'Texto oficial em português. Mostra simultaneamente a renovação bíblica do Vaticano II e sua declaração explícita de continuidade com Trento e Vaticano I, evitando tanto a tese de ruptura total quanto a de que nada mudou.',
    base: 'edição autorizada',
  },
  {
    id: 'vaticano2-gaudium-spes',
    autor: 'Concílio Vaticano II',
    ano: '1965',
    titulo: 'Gaudium et Spes — Constituição Pastoral sobre a Igreja no Mundo Atual',
    publicacao: 'Santa Sé',
    url: 'https://press.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651207_gaudium-et-spes_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'CG10', 'CG65'],
    nota: 'Documento oficial que formula a aproximação pastoral do Vaticano II às questões humanas, sociais e culturais do mundo moderno. É a ponte documental para a recepção latino-americana posterior.',
    base: 'edição autorizada',
  },
  {
    id: 'vaticano2-unitatis-redintegratio',
    autor: 'Concílio Vaticano II',
    ano: '1964',
    titulo: 'Unitatis Redintegratio — Decreto sobre o Ecumenismo',
    publicacao: 'Santa Sé',
    url: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19641121_unitatis-redintegratio_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS53'],
    nota: 'Texto oficial em português sobre a participação católica no movimento ecumênico. Útil para distinguir aproximação e diálogo de uma suposta dissolução automática das diferenças confessionais.',
    base: 'edição autorizada',
  },
  {
    id: 'celam-medellin-1968',
    autor: '2ª Conferência Geral do Episcopado Latino-Americano',
    ano: '1968',
    titulo: 'Medellín — Documento final de comissões',
    publicacao: 'Repositório oficial do CELAM',
    url: 'https://repositorio.celam.org/s/repositorio/item/3171',
    idioma: 'es',
    acesso: 'parcial',
    disciplinas: ['TH04', 'TH05', 'CG10'],
    nota: 'Ficha arquivística oficial do documento final de Medellín. O repositório oferece metadados, resumo institucional e contexto, mas informa que o tomo digital completo exige autorização; por isso o acesso está corretamente marcado como parcial.',
    base: 'edição autorizada',
  },
  {
    id: 'libertatis-nuntius-1984',
    autor: 'Congregação para a Doutrina da Fé',
    ano: '1984',
    titulo: 'Instrução sobre alguns aspectos da Teologia da Libertação — Libertatis Nuntius',
    publicacao: 'Santa Sé',
    url: 'https://www.vatican.va/roman_curia/congregations/cfaith/documents/rc_con_cfaith_doc_19840806_theology-liberation_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'TH05', 'CG65'],
    nota: 'Documento romano particularmente útil porque não reduz a Teologia da Libertação a um bloco homogêneo: reconhece a legitimidade bíblica do tema da libertação e da preocupação com justiça, ao mesmo tempo que critica apropriações de categorias marxistas consideradas incompatíveis com a fé cristã.',
    base: 'edição autorizada',
  },
  {
    id: 'lausanne-covenant-1974',
    autor: 'Congresso Internacional de Evangelização Mundial',
    ano: '1974',
    titulo: 'The Lausanne Covenant',
    publicacao: 'Lausanne Movement',
    url: 'https://lausanne.org/statement/lausanne-covenant',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP07', 'TH52', 'TS11'],
    nota: 'Texto integral do Pacto de Lausanne no site oficial do movimento. Articula autoridade bíblica, unicidade de Cristo, evangelização mundial e responsabilidade social, tornando-se uma referência decisiva para o evangelicalismo global posterior.',
    base: 'edição autorizada',
  },
];
