import type { ObraLivre } from './biblioteca';

/**
 * Fontes abertas acrescentadas na reta final de cobertura e nos ciclos de
 * aprofundamento curricular. Mantidas separadas do arquivo histórico para que
 * cada inclusão permaneça pequena, auditável e fácil de retirar/substituir se
 * um acervo mudar.
 */
export const bibliotecaFinal: ObraLivre[] = [
  {
    id: 'schaff-creeds-2',
    autor: 'Philip Schaff',
    ano: '1877',
    titulo: 'The Creeds of Christendom, vol. II — Greek and Latin Creeds',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://ccel.org/ccel/schaff/creeds2/creeds2.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS53', 'TH01', 'TH02'],
    nota: 'Reúne regras de fé antigas, Credo Apostólico, Niceia-Constantinopla, Calcedônia e outros símbolos em textos comparáveis. É a fonte aberta mais útil para acompanhar a formação dos credos ecumênicos sem depender de citações de segunda mão.',
    base: 'domínio público',
  },
  {
    id: 'orange-529',
    autor: 'Segundo Concílio de Orange',
    ano: '529',
    titulo: 'Canons of the Second Council of Orange, A.D. 529',
    publicacao: 'Open Library — edição de 1882',
    url: 'https://openlibrary.org/books/OL28397248M/Canons_of_the_Second_Council_of_Orange_A.D._529',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS53', 'TH02', 'TS04'],
    nota: 'Edição histórica em latim e inglês dos cânones sobre graça, pecado e livre-arbítrio. Permite situar Orange como testemunho ocidental anterior à Reforma sem projetar retrospectivamente sobre o concílio todo o sistema reformado posterior.',
    base: 'domínio público',
  },
  {
    id: 'wrf-statement-2011',
    autor: 'World Reformed Fellowship',
    ano: '2011',
    titulo: 'World Reformed Fellowship Statement of Faith',
    publicacao: 'World Reformed Fellowship',
    url: 'https://wrfnet.org/about/statement-of-faith',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS53'],
    nota: 'Página oficial da declaração concluída em 2011. A própria WRF explica que pretende expressar elementos comuns das confissões reformadas históricas, aplicar a fé a questões do século XXI e incluir vozes reformadas globais, sem substituir os símbolos históricos.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-postmodernism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2015',
    titulo: 'Postmodernism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/postmodernism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS54', 'CG65'],
    nota: 'Verbete acadêmico usado para distinguir pós-modernismo de caricaturas populares, situar Lyotard, Foucault, Derrida e seus precursores e mostrar a diversidade interna das correntes associadas ao rótulo.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-relativism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2020',
    titulo: 'Relativism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/relativism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS54', 'CG08', 'CG65'],
    nota: 'Panorama revisado por especialistas das diferentes famílias de relativismo. Ajuda a separar relativismo epistêmico, moral e outras formas da simples constatação de diversidade cultural ou da finitude do conhecedor.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-critical-theory',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2023',
    titulo: 'Critical Theory (Frankfurt School)',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/critical-theory/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS54', 'CG65'],
    nota: 'Verbete contemporâneo sobre a Escola de Frankfurt e os sentidos estrito e amplo de teoria crítica. Serve para distinguir tradições marxistas reais de usos totalizantes e conspiratórios da expressão “marxismo cultural”.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-religious-pluralism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2025',
    titulo: 'Religious Diversity (Pluralism)',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/religious-pluralism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TS54'],
    nota: 'Panorama acadêmico atualizado sobre diversidade religiosa, exclusivismo, pluralismo, desacordo e tolerância. É especialmente útil para não confundir o fato sociológico da diversidade com uma tese filosófica sobre a verdade ou eficácia salvífica de religiões incompatíveis.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-atheism-agnosticism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2022',
    titulo: 'Atheism and Agnosticism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/atheism-agnosticism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TS51', 'CG65'],
    nota: 'Distingue usos psicológicos, metafísicos e epistemológicos de ateísmo e agnosticismo. Evita que a apologética responda a uma definição diferente daquela que o interlocutor realmente sustenta.',
    base: 'edição autorizada',
  },
  {
    id: 'pickthall-koran-1930',
    autor: 'Muhammad Marmaduke Pickthall, trad.',
    ano: '1930',
    titulo: 'The Meaning of the Glorious Koran',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/The_Meaning_of_the_Glorious_Koran_(1930)',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TP56'],
    nota: 'Tradução inglesa produzida por um muçulmano. A edição de 1930 está em domínio público nos Estados Unidos desde 2026 e oferece acesso primário ao texto corânico; não substitui a diversidade da tradição interpretativa islâmica.',
    base: 'domínio público',
  },
  {
    id: 'gita-swarupananda-1909',
    autor: 'Swami Swarupananda, trad. e coment.',
    ano: '1909',
    titulo: 'Srimad-Bhagavad-Gita',
    publicacao: 'Internet Sacred Text Archive',
    url: 'https://archive.sacred-texts.com/hin/sbg/sbg00.htm',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TP56'],
    nota: 'Tradução e comentário hindu em domínio público. Permite observar ação, conhecimento, devoção, karma e libertação numa fonte da própria tradição, em vez de reduzir o hinduísmo a um slogan apologético.',
    base: 'domínio público',
  },
  {
    id: 'dhammapada-1920',
    autor: 'W. D. C. Wagiswara e K. J. Saunders, trads.',
    ano: '1920',
    titulo: "The Buddha's Way of Virtue — A Translation of the Dhammapada",
    publicacao: 'Internet Sacred Text Archive',
    url: 'https://www.sacred-texts.com/bud/wov/wov00.htm',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TP56'],
    nota: 'Tradução do Dhammapada em domínio público. É uma porta de entrada textual para desejo, conduta, mente e libertação, sem pretender representar sozinha Theravāda, Mahāyāna, Vajrayāna e demais tradições budistas.',
    base: 'domínio público',
  },
  {
    id: 'barmen-ekd-1934',
    autor: 'Sínodo Confessante da Igreja Evangélica Alemã',
    ano: '1934',
    titulo: 'The Theological Declaration of Barmen',
    publicacao: 'Evangelical Church in Germany (EKD)',
    url: 'https://www.ekd.de/en/The-Barmen-Declaration-303.htm',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS11', 'CG65'],
    nota: 'Texto integral da Declaração de Barmen no portal da Igreja Evangélica na Alemanha. É a fonte primária para estudar a resposta da Igreja Confessante à captura do protestantismo pelos chamados Cristãos Alemães e ao totalitarismo nazista.',
    base: 'edição autorizada',
  },
  {
    id: 'wcc-history-1948',
    autor: 'World Council of Churches',
    ano: '1948–2026',
    titulo: 'History of the World Council of Churches',
    publicacao: 'World Council of Churches',
    url: 'https://www.oikoumene.org/about-the-wcc/history',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TH52', 'TP07'],
    nota: 'História institucional do Conselho Mundial de Igrejas, fundado em Amsterdã em 1948. Permite acompanhar o ecumenismo por sua própria autodescrição, inclusive expansão global, missão, diálogo e ação social.',
    base: 'edição autorizada',
  },
  {
    id: 'vaticano2-dei-verbum',
    autor: 'Concílio Vaticano II',
    ano: '1965',
    titulo: 'Dei Verbum — Constituição Dogmática sobre a Revelação Divina',
    publicacao: 'Santa Sé',
    url: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651118_dei-verbum_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS01', 'TS53'],
    nota: 'Texto oficial em português. Mostra simultaneamente a renovação bíblica do Vaticano II e sua declaração explícita de continuidade com Trento e Vaticano I, evitando tanto a tese de ruptura total quanto a de que nada mudou.',
    base: 'edição autorizada',
  },
  {
    id: 'vaticano2-gaudium-spes',
    autor: 'Concílio Vaticano II',
    ano: '1965',
    titulo: 'Gaudium et Spes — Constituição Pastoral sobre a Igreja no Mundo Atual',
    publicacao: 'Santa Sé',
    url: 'https://press.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19651207_gaudium-et-spes_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'CG10', 'CG65'],
    nota: 'Documento oficial que formula a aproximação pastoral do Vaticano II às questões humanas, sociais e culturais do mundo moderno. É a ponte documental para a recepção latino-americana posterior.',
    base: 'edição autorizada',
  },
  {
    id: 'vaticano2-unitatis-redintegratio',
    autor: 'Concílio Vaticano II',
    ano: '1964',
    titulo: 'Unitatis Redintegratio — Decreto sobre o Ecumenismo',
    publicacao: 'Santa Sé',
    url: 'https://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_decree_19641121_unitatis-redintegratio_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS53'],
    nota: 'Texto oficial em português sobre a participação católica no movimento ecumênico. Útil para distinguir aproximação e diálogo de uma suposta dissolução automática das diferenças confessionais.',
    base: 'edição autorizada',
  },
  {
    id: 'celam-medellin-1968',
    autor: '2ª Conferência Geral do Episcopado Latino-Americano',
    ano: '1968',
    titulo: 'Medellín — Documento final de comissões',
    publicacao: 'Repositório oficial do CELAM',
    url: 'https://repositorio.celam.org/s/repositorio/item/3171',
    idioma: 'es',
    acesso: 'parcial',
    disciplinas: ['TH04', 'TH05', 'CG10'],
    nota: 'Ficha arquivística oficial do documento final de Medellín. O repositório oferece metadados, resumo institucional e contexto, mas informa que o tomo digital completo exige autorização; por isso o acesso está corretamente marcado como parcial.',
    base: 'edição autorizada',
  },
  {
    id: 'libertatis-nuntius-1984',
    autor: 'Congregação para a Doutrina da Fé',
    ano: '1984',
    titulo: 'Instrução sobre alguns aspectos da Teologia da Libertação — Libertatis Nuntius',
    publicacao: 'Santa Sé',
    url: 'https://www.vatican.va/roman_curia/congregations/cfaith/documents/rc_con_cfaith_doc_19840806_theology-liberation_po.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH04', 'TH05', 'CG65'],
    nota: 'Documento romano particularmente útil porque não reduz a Teologia da Libertação a um bloco homogêneo: reconhece a legitimidade bíblica do tema da libertação e da preocupação com justiça, ao mesmo tempo que critica apropriações de categorias marxistas consideradas incompatíveis com a fé cristã.',
    base: 'edição autorizada',
  },
  {
    id: 'lausanne-covenant-1974',
    autor: 'Congresso Internacional de Evangelização Mundial',
    ano: '1974',
    titulo: 'The Lausanne Covenant',
    publicacao: 'Lausanne Movement',
    url: 'https://lausanne.org/statement/lausanne-covenant',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP07', 'TH52', 'TS11'],
    nota: 'Texto integral do Pacto de Lausanne no site oficial do movimento. Articula autoridade bíblica, unicidade de Cristo, evangelização mundial e responsabilidade social, tornando-se uma referência decisiva para o evangelicalismo global posterior.',
    base: 'edição autorizada',
  },
];
