import type { ObraLivre } from './biblioteca';

/** Fontes acadêmicas abertas para os ciclos de filosofia e áreas afins. */
export const bibliotecaFilosofia: ObraLivre[] = [
  {
    id: 'sep-aristotle-metaphysics',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2025',
    titulo: 'Aristotle’s Metaphysics',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/aristotle-metaphysics/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09'],
    nota: 'Verbete acadêmico revisado por especialistas sobre ser enquanto ser, substância, essência, matéria e forma, ato e potência e a relação entre primeira filosofia e teologia em Aristóteles. Serve para ensinar a metafísica aristotélica sem reduzi-la a uma lista de termos escolásticos posteriores.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-logical-empiricism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2022',
    titulo: 'Logical Empiricism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/logical-empiricism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09', 'CG65'],
    nota: 'Panorama acadêmico do empirismo lógico, do Círculo de Viena, do verificacionismo e das críticas à metafísica. É usado para mostrar a diversidade interna do movimento e evitar a caricatura de que todos os positivistas sustentaram exatamente a mesma tese.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-heidegger',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2025',
    titulo: 'Martin Heidegger',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/heidegger/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09', 'CG65'],
    nota: 'Introdução acadêmica à pergunta pelo ser, à diferença ontológica, à analítica do Dasein e à crítica heideggeriana da tradição metafísica. Permite tratar a “reconstrução da metafísica” da ementa sem apresentar Heidegger como simples restaurador da metafísica clássica.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-modal-logic',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Modal Logic',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/logic-modal/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG58'],
    nota: 'Tratamento acadêmico de necessidade, possibilidade, sistemas modais e semântica de mundos possíveis, incluindo a contribuição de Saul Kripke. É a base aberta para a unidade curricular sobre metafísica das modalidades.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-epistemology',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2024',
    titulo: 'Epistemology',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/epistemology/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09'],
    nota: 'Panorama acadêmico da teoria do conhecimento: natureza do conhecimento, justificação, fontes epistêmicas, ceticismo e principais famílias contemporâneas. Complementa o debate fé–razão já existente no portal com o vocabulário técnico da disciplina.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-metaethics',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2023',
    titulo: 'Metaethics',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/metaethics/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'TS10'],
    nota: 'Introdução revisada por especialistas às perguntas metafísicas, epistemológicas e semânticas por trás da linguagem moral: fatos morais, relativismo, naturalismo, motivação, razões e o problema de Eutífron.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-aesthetic-concept',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2026',
    titulo: 'The Concept of the Aesthetic',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/aesthetic-concept/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09', 'TS12'],
    nota: 'Verbete acadêmico atualizado sobre experiência, julgamento e valor estéticos, incluindo a tradição moderna do gosto e a questão da objetividade dos juízos de beleza. Sustenta a unidade de estética sem reduzir beleza a preferência privada nem tratá-la como conceito simples.',
    base: 'edição autorizada',
  },
];
