import type { ObraLivre } from './biblioteca';

/** Fontes primárias e abertas para o aprofundamento de História da Igreja 3. */
export const bibliotecaReforma: ObraLivre[] = [
  {
    id: 'knox-reformation-scotland',
    autor: 'John Knox',
    ano: 'c. 1566',
    titulo: 'The History of the Reformation of Religion in Scotland',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/48250',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03'],
    nota: 'Relato de primeira mão de Knox sobre a Reforma escocesa, acompanhado da Confissão atribuída ao movimento e do Book of Discipline. É fonte participante, portanto valiosa justamente quando lida junto de uma história crítica mais ampla.',
    base: 'domínio público',
  },
  {
    id: 'ignatius-spiritual-exercises-pg',
    autor: 'Inácio de Loyola; adaptação de Charles Coppens',
    ano: '1522–1524; ed. 1916',
    titulo: 'The Spiritual Exercises of St. Ignatius — adaptação para retiro',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/70790',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03'],
    nota: 'Edição em domínio público de uma adaptação dos Exercícios Espirituais. Permite observar a disciplina espiritual e o discernimento inaciano a partir de um texto da própria tradição jesuíta; não deve ser confundida com uma edição crítica do original espanhol.',
    base: 'domínio público',
  },
  {
    id: 'schaff-creeds-2',
    autor: 'Philip Schaff (ed.)',
    ano: '1877',
    titulo: 'The Creeds of Christendom, vol. II — Greek and Latin Creeds',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://ccel.org/ccel/schaff/creeds2.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03', 'TS11', 'TS53'],
    nota: 'Reúne em domínio público o texto latino e tradução inglesa dos cânones e decretos dogmáticos do Concílio de Trento. Permite comparar diretamente as respostas tridentinas sobre Escritura, pecado, justificação e sacramentos com as formulações protestantes.',
    base: 'domínio público',
  },
  {
    id: 'bradford-plymouth-plantation',
    autor: 'William Bradford',
    ano: '1630–1651',
    titulo: "Bradford's History of 'Plimoth Plantation'",
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/24950',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03', 'TH04'],
    nota: 'Relato primário de Bradford sobre os separatistas ingleses, a passagem pelos Países Baixos, a viagem do Mayflower e a formação de Plymouth. Deve ser lido como memória participante, não como relato neutro da colonização.',
    base: 'domínio público',
  },
  {
    id: 'john-smith-virginia-historie',
    autor: 'John Smith',
    ano: '1624',
    titulo: 'The General Historie of Virginia, New England & the Summer Isles, vol. I',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/56347',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03'],
    nota: 'Fonte primária sobre os primeiros empreendimentos ingleses na Virgínia e na costa atlântica. É útil para estudar a matriz anglicana e comercial da Virgínia, mas exige leitura crítica por refletir a perspectiva de um agente da colonização.',
    base: 'domínio público',
  },
];
