import type { Idioma, NivelAcesso } from '../tipos';

/**
 * Obras de referência disponíveis legalmente sem custo.
 *
 * Critério de entrada, deliberadamente estreito: domínio público, edição
 * digital autorizada pelo detentor dos direitos, ou empréstimo digital
 * controlado de biblioteca. Cópia não autorizada de obra em catálogo NÃO
 * entra — nem por conveniência. Além de ser errado com quem publica em
 * português, esses links morrem, e um portal de estudo não pode ser
 * construído sobre eles.
 *
 * Quando a obra de referência ainda está em catálogo, a resposta do portal
 * não é indicar uma cópia pirata: é ensinar a doutrina no próprio verbete,
 * com o aparato primário aberto listado aqui.
 */
export interface ObraLivre {
  id: string;
  autor: string;
  ano: string;
  titulo: string;
  publicacao: string;
  url: string;
  idioma: Idioma;
  acesso: NivelAcesso;
  /** Códigos de disciplina que esta obra serve. */
  disciplinas: string[];
  /** Por que vale a pena, e o que ela substitui. */
  nota: string;
  /** Por que é lícito estar aqui. */
  base: 'domínio público' | 'edição autorizada' | 'empréstimo de biblioteca';
}

export const biblioteca: ObraLivre[] = [
  {
    id: 'calvino-institutas',
    autor: 'João Calvino',
    ano: '1559',
    titulo: 'Institutes of the Christian Religion (trad. Beveridge)',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/calvin/institutes.all.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07', 'TS11', 'TS12', 'CG59', 'TP52'],
    nota: 'A obra fundadora da dogmática reformada, em texto integral. Percorre praticamente todo o programa de Teologia Sistemática dos quatro anos. Se você só puder ler uma obra primária, leia esta.',
    base: 'domínio público',
  },
  {
    id: 'calvino-institutas-pdf',
    autor: 'João Calvino',
    ano: '1559',
    titulo: 'The Institutes of the Christian Religion — PDF integral',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/calvin/institutes/formats/institutes.pdf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07'],
    nota: 'Mesma tradução em arquivo único, para leitura offline e citação por página.',
    base: 'domínio público',
  },
  {
    id: 'calvino-romanos',
    autor: 'João Calvino',
    ano: '1540',
    titulo: 'Commentary on Romans',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/calvin/calcom38.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE12', 'TE13', 'TE20', 'TE21', 'TS04', 'TE16'],
    nota: 'O primeiro comentário de Calvino e o manifesto do método exegético reformado. A epístola dedicatória é leitura obrigatória em Hermenêutica.',
    base: 'domínio público',
  },
  {
    id: 'hodge-st1',
    autor: 'Charles Hodge',
    ano: '1872',
    titulo: 'Systematic Theology — vol. I: Teologia',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/hodge/theology1.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01'],
    nota: 'Prolegômenos, Bibliologia e Teontologia em exposição completa. Cobre integralmente o programa de TS01 e é a matriz de Princeton por trás de boa parte dos manuais em português.',
    base: 'domínio público',
  },
  {
    id: 'hodge-st2',
    autor: 'Charles Hodge',
    ano: '1872',
    titulo: 'Systematic Theology — vol. II: Antropologia',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/hodge/theology2.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS02', 'TS03'],
    nota: 'Criação, imagem de Deus, pacto das obras, queda, pecado original e livre-arbítrio: o programa de TS02 inteiro.',
    base: 'domínio público',
  },
  {
    id: 'hodge-st3-pdf',
    autor: 'Charles Hodge',
    ano: '1873',
    titulo: 'Systematic Theology — vol. III: Soteriologia e Escatologia (PDF)',
    publicacao: 'CCEL',
    url: 'https://www.ccel.org/ccel/h/hodge/theology3/cache/theology3.pdf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TS06', 'TS07'],
    nota: 'Vocação, regeneração, fé, justificação, santificação, meios da graça e últimas coisas.',
    base: 'domínio público',
  },
  {
    id: 'bavinck-gd1',
    autor: 'Herman Bavinck',
    ano: '1895',
    titulo: 'Gereformeerde Dogmatiek — Deel 1',
    publicacao: 'Digitale Bibliotheek voor de Nederlandse Letteren (DBNL)',
    url: 'https://www.dbnl.org/tekst/bavi002gere01_01/',
    idioma: 'nl',
    acesso: 'livre',
    disciplinas: ['TS01'],
    nota: 'O original holandês, em domínio público e texto integral. A tradução inglesa em quatro volumes custa algumas centenas de reais; o holandês de Bavinck é surpreendentemente acessível com dicionário, e este volume é a melhor exposição existente da doutrina dos princípios.',
    base: 'domínio público',
  },
  {
    id: 'bavinck-gd-obra',
    autor: 'Herman Bavinck',
    ano: '1895-1901',
    titulo: 'Gereformeerde Dogmatiek — os quatro volumes',
    publicacao: 'DBNL',
    url: 'https://www.dbnl.org/tekst/bavi002gere00_01/',
    idioma: 'nl',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07'],
    nota: 'Página da obra completa, com acesso aos quatro volumes e aos PDFs. A dogmática reformada mais equilibrada já escrita.',
    base: 'domínio público',
  },
  {
    id: 'bavinck-rd-monergism',
    autor: 'Herman Bavinck',
    ano: '1895',
    titulo: 'Reformed Dogmatics — página de acesso',
    publicacao: 'Monergism',
    url: 'https://www.monergism.com/reformed-dogmatics-ebook',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07'],
    nota: 'Para quem lê inglês com mais conforto que holandês.',
    base: 'edição autorizada',
  },
  {
    id: 'turretin-latim',
    autor: 'Francis Turretin',
    ano: '1679',
    titulo: 'Institutio Theologiae Elencticae',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/institutiotheol00turrgoog',
    idioma: 'la',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS11', 'TS53'],
    nota: 'O ápice da escolástica reformada, em latim e domínio público. É a fonte por trás das distinções técnicas que os manuais modernos repetem sem citar.',
    base: 'domínio público',
  },
  {
    id: 'turretin-ingles',
    autor: 'Francis Turretin',
    ano: '1679',
    titulo: 'Institutes of Elenctic Theology (trad. Giger)',
    publicacao: 'Internet Archive — empréstimo digital',
    url: 'https://archive.org/details/institutesofelen0001turr',
    idioma: 'en',
    acesso: 'cadastro',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04'],
    nota: 'A tradução ainda está em catálogo; o Internet Archive a empresta por tempo limitado, com conta gratuita. É empréstimo de biblioteca, não download.',
    base: 'empréstimo de biblioteca',
  },
  {
    id: 'cfw-ipib',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'Confissão de Fé de Westminster',
    publicacao: 'Igreja Presbiteriana Independente do Brasil',
    url: 'https://ipib.org.br/confissao-de-fe-de-westminster/',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53', 'TP12', 'TP13', 'TP25', 'TE16', 'TP04', 'CG59'],
    nota: 'O padrão subordinado da IPB, em português. Base direta de TS11 (Símbolos de Fé) e referência constante em toda a Sistemática.',
    base: 'domínio público',
  },
  {
    id: 'cfw-braga',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'A Confissão de Fé de Westminster — edição portuguesa',
    publicacao: 'Igreja Cristã Presbiteriana de Braga',
    url: 'https://www.icpbraga.pt/documentos/cfw',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53'],
    nota: 'Útil para cotejo de tradução: onde as duas versões divergem, quase sempre há uma decisão interpretativa por trás.',
    base: 'domínio público',
  },
  {
    id: 'cfw-ipcambe',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'Confissão de Fé de Westminster — cap. I, Da Escritura Sagrada',
    publicacao: 'Igreja Presbiteriana de Cambé (IPB)',
    url: 'https://ipcambe.ipb.org.br/boletim/confissao-de-fe-de-westminster',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS11'],
    nota: 'Hospedada em domínio da própria IPB.',
    base: 'domínio público',
  },
  {
    id: 'monergismo',
    autor: 'Vários',
    ano: '—',
    titulo: 'Monergismo — acervo de teologia reformada em português',
    publicacao: 'monergismo.com',
    url: 'https://www.monergismo.com/',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07', 'TE12', 'TH01'],
    nota: 'O maior acervo lusófono de textos reformados traduzidos e disponibilizados com autorização. Primeira parada para quem lê só em português.',
    base: 'edição autorizada',
  },
  {
    id: 'ccel',
    autor: 'Vários',
    ano: '—',
    titulo: 'Christian Classics Ethereal Library',
    publicacao: 'ccel.org',
    url: 'https://www.ccel.org/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TH01', 'TH02', 'TH03', 'TH07', 'TE12'],
    nota: 'Milhares de clássicos cristãos em domínio público, com texto navegável e PDF. Padres, medievais, reformadores e puritanos.',
    base: 'domínio público',
  },
  {
    id: 'dbnl',
    autor: 'Vários',
    ano: '—',
    titulo: 'Digitale Bibliotheek voor de Nederlandse Letteren',
    publicacao: 'dbnl.org',
    url: 'https://www.dbnl.org/',
    idioma: 'nl',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS12', 'TH04'],
    nota: 'O acervo digital das letras holandesas. Indispensável para a tradição neocalvinista — Bavinck, Kuyper e a discussão da cosmovisão em TS12.',
    base: 'domínio público',
  },
  {
    id: 'archive',
    autor: 'Vários',
    ano: '—',
    titulo: 'Internet Archive',
    publicacao: 'archive.org',
    url: 'https://archive.org/',
    idioma: 'en',
    acesso: 'parcial',
    disciplinas: ['TS01', 'TH01', 'TH05', 'TH06'],
    nota: 'Domínio público em download livre e obras em catálogo por empréstimo digital com conta gratuita. Atenção ao distinguir os dois casos.',
    base: 'empréstimo de biblioteca',
  },
  {
    id: 'schaff-hcc',
    autor: 'Philip Schaff',
    ano: '1858-1890',
    titulo: 'History of the Christian Church (8 volumes)',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/schaff/hcc2.all.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01', 'TH02', 'TH03', 'TH04', 'TH07', 'TH08'],
    nota: 'A história da Igreja padrão em língua inglesa, em domínio público. Sozinha cobre o programa dos quatro semestres de História da Igreja — substituto direto de qualquer manual em catálogo.',
    base: 'domínio público',
  },
  {
    id: 'anf',
    autor: 'Roberts e Donaldson (eds.)',
    ano: '1885',
    titulo: 'Ante-Nicene Fathers — os padres anteriores a Niceia',
    publicacao: 'CCEL',
    url: 'https://ccel.org/ccel/schaff/anf01/anf01.i.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01', 'TH07', 'TS01'],
    nota: 'As fontes primárias dos dois primeiros séculos em tradução: Clemente, Inácio, Policarpo, a Didaqué, Justino Mártir e o Contra as Heresias de Irineu.',
    base: 'domínio público',
  },
  {
    id: 'schaff-archive',
    autor: 'Philip Schaff',
    ano: '1885',
    titulo: 'History of the Christian Church, vol. II — cópia alternativa',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/historyofthechri009648mbp',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01'],
    nota: 'Alternativa ao CCEL, que recusa conexões vindas de faixas de IP de nuvem.',
    base: 'domínio público',
  },
  {
    id: 'spurgeon-lectures',
    autor: 'Charles Haddon Spurgeon',
    ano: '1877',
    titulo: 'Lectures to My Students',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/lecturestomystud1877spur',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP14', 'TP01', 'TP02', 'TP15'],
    nota: 'As palestras de Spurgeon aos alunos do Pastors College, em domínio público. Ainda hoje o tratado mais útil sobre a vida, o preparo e a entrega do pregador.',
    base: 'domínio público',
  },
  {
    id: 'spurgeon-segunda',
    autor: 'Charles Haddon Spurgeon',
    ano: '1877',
    titulo: 'Second Series of Lectures to My Students',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/secondseriesofle00spur',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP14'],
    nota: 'A segunda série trata sobretudo da voz e da entrega — o material da unidade 4 do programa de Homilética.',
    base: 'domínio público',
  },
  {
    id: 'vos-idea-bt',
    autor: 'Geerhardus Vos',
    ano: '1894',
    titulo: 'The Idea of Biblical Theology as a Science and as a Theological Discipline',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/inaugurationofrevge00prin',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE14', 'TE15', 'TE12'],
    nota: 'A aula inaugural em Princeton que fundou a teologia bíblica em bases reformadas. Curta — cabe numa tarde — e contém a distinção entre processo e produto que organiza a disciplina inteira. É o melhor ponto de entrada gratuito para TE14.',
    base: 'domínio público',
  },
  {
    id: 'vos-reino',
    autor: 'Geerhardus Vos',
    ano: '1903',
    titulo: 'The Teaching of Jesus Concerning the Kingdom of God and the Church',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/theteachingofjes00vosuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE15', 'TP07', 'TS07', 'TS06'],
    nota: 'Demonstra que o reino é presente e futuro no próprio ensino de Jesus, e que a igreja é a forma que ele assume no intervalo. É a raiz da escatologia inaugurada que os manuais caros de escatologia resumem em poucas páginas.',
    base: 'domínio público',
  },
  {
    id: 'vos-self-disclosure',
    autor: 'Geerhardus Vos',
    ano: '1926',
    titulo: 'The Self-Disclosure of Jesus',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/selfdisclosureof00vosg_0',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE15', 'TS03'],
    nota: 'Como Jesus revela a própria identidade nos evangelhos, com resposta à crítica liberal que separava o Jesus da história do Cristo da fé. Complementa o volume sobre o reino pelo lado cristológico.',
    base: 'domínio público',
  },
  {
    id: 'warfield-lord-of-glory',
    autor: 'Benjamin B. Warfield',
    ano: '1907',
    titulo: 'The Lord of Glory: os títulos de Cristo no Novo Testamento',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/lordofglorystud00warf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS03', 'TE15', 'TS51'],
    nota: 'Levantamento corpo a corpo — sinóticos, João, Paulo, Hebreus — de cada designação dada a Cristo. Serve para verificar por conta própria se a alta cristologia é acréscimo tardio ou está nos textos mais antigos, em vez de aceitar a resposta de um manual.',
    base: 'domínio público',
  },
  {
    id: 'machen-liberalismo',
    autor: 'J. Gresham Machen',
    ano: '1923',
    titulo: 'Christianity and Liberalism',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/christianitylibe00mach_0',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TS11', 'TS54', 'TS51'],
    nota: 'Compara ponto a ponto — Deus, homem, Bíblia, Cristo, salvação, igreja — as duas teologias que dividiam as mesmas denominações no início do século XX. Continua sendo a exposição mais clara do que estava em jogo, e o livro é curto.',
    base: 'domínio público',
  },
  {
    id: 'edwards-avivamentos',
    autor: 'Jonathan Edwards',
    ano: '1737–1742',
    titulo: 'Edwards on Revivals: A Faithful Narrative e Thoughts on the Revival',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/edwardsonrevival00edwa',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH04', 'TP09', 'TS05', 'CG62'],
    nota: 'Um volume com o relato de 1737 e a defesa crítica de 1742 — Edwards defendendo o avivamento e submetendo-o a exame no mesmo lugar. Leitura obrigatória para quem precisa avaliar movimentos contemporâneos sem cair no entusiasmo nem no ceticismo automático.',
    base: 'domínio público',
  },
  {
    id: 'edwards-afeicoes',
    autor: 'Jonathan Edwards',
    ano: '1746',
    titulo: 'A Treatise Concerning Religious Affections',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/treatiseconcerni1746edwa',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TS05', 'TP03', 'TH04', 'CG62'],
    nota: 'A obra que distingue, sinal por sinal, o que não prova nada sobre uma experiência religiosa do que a caracteriza como obra do Espírito. Substitui uma prateleira inteira de literatura sobre segurança da salvação e discernimento espiritual.',
    base: 'domínio público',
  },
  {
    id: 'carey-enquiry',
    autor: 'William Carey',
    ano: '1792',
    titulo: 'An Enquiry into the Obligations of Christians to Use Means for the Conversion of the Heathens',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/pts_enquiryintotheobligations_1687_2',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP07', 'TP08', 'TH04', 'TH51', 'TP25'],
    nota: 'O opúsculo que abriu o período moderno das missões protestantes, com o argumento de que a comissão e a promessa que a acompanha duram o mesmo tanto — seguido das tabelas de população e religião por região. Reprodução do original de 1792.',
    base: 'domínio público',
  },
  {
    id: 'warneck-missoes',
    autor: 'Gustav Warneck',
    ano: '1901',
    titulo: 'Outline of a History of Protestant Missions from the Reformation to the Present Time',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/outlineofhistory00warn',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP07', 'TP08', 'TH04', 'TH51', 'TP25'],
    nota: 'Panorama escrito pelo autor que fundou a missiologia como disciplina acadêmica. Cobre tanto o longo período em que o protestantismo não fez missões quanto a explosão de sociedades a partir de 1792 — a matéria de TH51 inteira.',
    base: 'domínio público',
  },
  {
    id: 'baxter-reformed-pastor',
    autor: 'Richard Baxter',
    ano: '1656',
    titulo: 'The Reformed Pastor',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/reformedpastor00baxt',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP01', 'TP02', 'TP03', 'TP10', 'TP04'],
    nota: 'O clássico sobre o cuidado pastoral pessoa a pessoa, escrito por quem catequizava família por família em Kidderminster. É a obra que está por trás de quase todo manual moderno de teologia pastoral — e sai de graça.',
    base: 'domínio público',
  },
  {
    id: 'owen-mortification',
    autor: 'John Owen',
    ano: '1656',
    titulo: 'The Mortification of Sin in Believers',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/mortificationofs00owen',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TP03', 'TP01', 'TP04'],
    nota: 'O tratado puritano sobre a luta contra o pecado no crente. Trata em detalhe do que a literatura devocional atual costuma resolver em slogan, e é a referência de fundo do aconselhamento reformado.',
    base: 'domínio público',
  },
  {
    id: 'owen-death-of-death',
    autor: 'John Owen',
    ano: '1648',
    titulo: 'The Death of Death in the Death of Christ',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/deathofdeathinde00owen',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS03', 'TS04'],
    nota: 'A defesa clássica da expiação definida, discutindo a extensão da obra de Cristo com um rigor que nenhum resumo reproduz. Quem quer avaliar a controvérsia sobre o alcance da expiação deve ler a peça de acusação no original, e ela está aqui.',
    base: 'domínio público',
  },
  {
    id: 'ryle-holiness',
    autor: 'J. C. Ryle',
    ano: '1887',
    titulo: 'Holiness: Its Nature, Hindrances, Difficulties and Roots',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/HolinessJ.C.Ryle1887',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS04', 'TP01', 'TP03'],
    nota: 'Escrito contra a ideia de que a santificação seria uma segunda bênção recebida de uma vez. Direto, pastoral e sem jargão — o livro mais acessível desta lista para quem está começando.',
    base: 'domínio público',
  },
  {
    id: 'boston-fourfold',
    autor: 'Thomas Boston',
    ano: '1720',
    titulo: 'Human Nature in Its Fourfold State',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/humannatureinits00bostuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS02', 'TS04', 'TP14', 'TP04'],
    nota: 'Antropologia teológica em quatro estados — inocência, corrupção, graça e glória. Cobre o programa de TS02 em forma de pregação, o que o torna útil também como modelo de como se prega doutrina.',
    base: 'domínio público',
  },
  {
    id: 'aa-hodge-outlines',
    autor: 'A. A. Hodge',
    ano: '1878',
    titulo: 'Outlines of Theology',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/outlinesoftheolo1878hodg',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS02', 'TS03', 'TS04', 'TS05', 'TS06', 'TS07', 'TS11'],
    nota: 'Sistemática reformada completa em pergunta e resposta, bem mais curta que os três volumes do pai. É a melhor opção gratuita para quem quer um manual de consulta rápida em vez de uma obra para ler de ponta a ponta.',
    base: 'domínio público',
  },
  {
    id: 'kuyper-calvinismo',
    autor: 'Abraham Kuyper',
    ano: '1898',
    titulo: 'Calvinism: Six Lectures (Stone Lectures, Princeton)',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/calvinismsixlect00kuyp',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS12', 'TS51', 'TS54', 'CG08', 'TP52'],
    nota: 'As seis conferências que apresentaram o calvinismo como sistema de vida — religião, política, ciência, arte — e de onde vem quase todo o vocabulário atual de cosmovisão, inclusive a soberania nas esferas. É a fonte que os livros de cosmovisão citam.',
    base: 'domínio público',
  },
  {
    id: 'schaff-creeds-3',
    autor: 'Philip Schaff',
    ano: '1877',
    titulo: 'The Creeds of Christendom, vol. III — as confissões protestantes',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/TheCreedsOfChristendomV3',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53', 'TH03'],
    nota: 'Os textos das confissões protestantes reunidos e comparados, com o original ao lado da tradução. Permite conferir por conta própria o que Westminster, Heidelberg, Dort e a Confissão Belga de fato dizem, em vez de depender de citações de segunda mão.',
    base: 'domínio público',
  },
  {
    id: 'matthew-henry',
    autor: 'Matthew Henry',
    ano: '1710',
    titulo: 'An Exposition of the Old and New Testament (6 volumes)',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/expositionofoldn11henr',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE12', 'TE13', 'TE20', 'TE21', 'TP15', 'TP16', 'TP17', 'TP18', 'TP19', 'TE16'],
    nota: 'Comentário de toda a Bíblia, versículo a versículo, com aplicação. Não substitui um comentário técnico para exegese em hebraico ou grego, mas resolve a maior parte das dúvidas de sentido e é o recurso gratuito mais completo para preparação de sermão.',
    base: 'domínio público',
  },
  {
    id: 'schaff-hcc3',
    autor: 'Philip Schaff',
    ano: '1889',
    titulo: 'History of the Christian Church, vol. III — Niceia e a igreja pós-nicena',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/schaff/hcc3.all.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH02', 'TS03', 'TS01'],
    nota: 'O volume que cobre o período dos concílios — Niceia, Constantinopla, Éfeso, Calcedônia — com os documentos e o contexto político. É a matéria de TH02 em fonte primária narrada.',
    base: 'domínio público',
  },
  {
    id: 'nicea-wikisource',
    autor: 'Concílio de Niceia',
    ano: '325',
    titulo: 'O Símbolo Niceno — texto e notas',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/Nicene_and_Post-Nicene_Fathers:_Series_II/Volume_XIV/The_First_Ecumenical_Council/The_Nicene_Creed',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS01', 'TS03', 'TH02', 'TS53'],
    nota: 'O texto do credo com as notas históricas da coleção Nicene and Post-Nicene Fathers. Vale ler o documento em vez de a paráfrase: é curto, e a palavra que dividiu a igreja no século IV está nele.',
    base: 'domínio público',
  },
  {
    id: 'calcedonia-wikisource',
    autor: 'Concílio de Calcedônia',
    ano: '451',
    titulo: 'A Definição de Fé de Calcedônia',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/Nicene_and_Post-Nicene_Fathers:_Series_II/Volume_XIV/The_Fourth_Ecumenical_Council/The_Definition_of_Faith',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS03', 'TH02', 'TS53'],
    nota: 'A definição que fixou o vocabulário da cristologia — uma pessoa, duas naturezas, e os quatro advérbios negativos. Cabe em uma página e é a base de tudo o que os manuais de cristologia discutem depois.',
    base: 'domínio público',
  },
  {
    id: 'eusebio-he',
    autor: 'Eusébio de Cesareia',
    ano: '325',
    titulo: 'História Eclesiástica, livro III — os escritos reconhecidos e os disputados',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/Nicene_and_Post-Nicene_Fathers:_Series_II/Volume_I/Church_History_of_Eusebius/Book_III/Chapter_25',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE02', 'TE01', 'TH01'],
    nota: 'O capítulo em que Eusébio classifica os livros em reconhecidos, disputados e espúrios — a fonte antiga mais citada nas discussões sobre a formação do cânon, disponível de graça em vez de resumida num manual de introdução ao Novo Testamento.',
    base: 'domínio público',
  },
  {
    id: 'spurgeon-soul-winner',
    autor: 'Charles Haddon Spurgeon',
    ano: '1895',
    titulo: 'The Soul Winner',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/soulwinner0000chsp',
    idioma: 'en',
    acesso: 'cadastro',
    disciplinas: ['TP09', 'TP14', 'TP59'],
    nota: 'Sobre evangelização feita por um calvinista convicto, o que a torna útil justamente para quem não vê como as duas coisas se juntam. Empréstimo digital controlado: exige conta gratuita no Internet Archive.',
    base: 'empréstimo de biblioteca',
  },
  {
    id: 'manual-presbiteriano',
    autor: 'Igreja Presbiteriana do Brasil',
    ano: '2025',
    titulo: 'Manual Presbiteriano — edição revista com notas remissivas',
    publicacao: 'Igreja Presbiteriana do Brasil',
    url: 'https://www.ipb.org.br/content/Downloads/manual_presbiteriano_2025.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP12', 'TP13', 'TP02', 'TP06', 'TS11', 'TP52'],
    nota: 'Traz a Constituição da IPB, os códigos e as resoluções em vigor, com notas remissivas. É a referência de trabalho de quem exerce ofício na denominação, e dispensa a compra do volume impresso.',
    base: 'edição autorizada',
  },
  {
    id: 'breve-catecismo',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'O Breve Catecismo de Westminster',
    publicacao: 'Igreja Presbiteriana do Brasil',
    url: 'https://www.ipb.org.br/content/Arquivos/Breve_Catecismo_de_Westminster.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53', 'TP10', 'TS01'],
    nota: 'As 107 perguntas e respostas, em português, publicadas pela própria denominação. A biblioteca tinha a Confissão em três edições e nenhum dos catecismos — e é o catecismo, não a Confissão, que foi feito para ser ensinado a quem está começando.',
    base: 'domínio público',
  },
  {
    id: 'sep',
    autor: 'Universidade Stanford',
    ano: '1995–',
    titulo: 'Stanford Encyclopedia of Philosophy',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08', 'CG09', 'CG65', 'CG58', 'TS51'],
    nota: 'Enciclopédia filosófica revisada por pares, com verbetes assinados por especialistas e bibliografia atualizada. Substitui integralmente os manuais caros de história da filosofia para consulta, e é a única obra desta lista escrita para o leitor de hoje.',
    base: 'edição autorizada',
  },
  {
    id: 'lery-pt',
    autor: 'Jean de Léry',
    ano: '1578',
    titulo: 'História de uma viagem feita à terra do Brasil',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/historiadeumavia00lery',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'TH01', 'CG11', 'CG63'],
    nota: 'Relato de testemunha ocular da colônia calvinista na Guanabara (1557), com a Confissão da Guanabara — a primeira confissão reformada das Américas — e a execução dos três que a assinaram. É também um dos primeiros registros etnográficos sobre os tupinambás. Uma das raras fontes primárias desta lista disponíveis em português.',
    base: 'domínio público',
  },
  {
    id: 'lery-fr',
    autor: 'Jean de Léry',
    ano: '1578',
    titulo: 'Histoire d’un voyage fait en la terre du Brésil — edição original',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/histoiredunvoyag01lryj',
    idioma: 'fr',
    acesso: 'livre',
    disciplinas: ['TH05'],
    nota: 'A primeira edição, de La Rochelle, para conferir passagens em que as traduções divergem — sobretudo nos capítulos sobre o rompimento com Villegagnon.',
    base: 'domínio público',
  },
  {
    id: 'simonton-sermoes',
    autor: 'Ashbel Green Simonton',
    ano: '1867',
    titulo: 'Sermões escolhidos',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/sermoesescolhido00simo',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'TH06', 'TP14', 'TP26'],
    nota: 'Os sermões do fundador do presbiterianismo brasileiro, em português. Permite ver em fonte primária o que ele de fato pregava, em vez de depender da imagem construída depois — e serve de amostra de homilética do século XIX no Brasil.',
    base: 'domínio público',
  },
  {
    id: 'codex-sinaiticus',
    autor: 'British Library e parceiros',
    ano: 'séc. IV',
    titulo: 'Codex Sinaiticus — manuscrito digitalizado com transcrição',
    publicacao: 'Codex Sinaiticus Project',
    url: 'https://www.codexsinaiticus.org/en/manuscript.aspx',
    idioma: 'grc',
    acesso: 'livre',
    disciplinas: ['TE52', 'TE02', 'TE08', 'TE09', 'TS01'],
    nota: 'A cópia completa mais antiga do Novo Testamento, do século IV, reunida digitalmente pelas quatro instituições que guardam suas partes. Imagem da página ao lado da transcrição palavra por palavra, com as correções de mãos posteriores marcadas. Serve também de material de leitura para quem estuda grego.',
    base: 'edição autorizada',
  },
  {
    id: 'kenyon-manuscritos',
    autor: 'Frederic G. Kenyon',
    ano: '1895',
    titulo: 'Our Bible and the Ancient Manuscripts',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/ourbibleancient00keny',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE52', 'TE01', 'TE02'],
    nota: 'Introdução clássica à transmissão do texto bíblico, escrita pelo então diretor do Museu Britânico para leigos. Anterior aos papiros do século XX, portanto desatualizada em achados, mas insuperada como explicação de como o trabalho é feito.',
    base: 'domínio público',
  },
  {
    id: 'westcott-hort',
    autor: 'B. F. Westcott e F. J. A. Hort',
    ano: '1882',
    titulo: 'The New Testament in the Original Greek: Introduction and Appendix',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/newtestamentinor82west',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE52', 'TE02', 'TE16'],
    nota: 'O volume que expõe o método por trás da edição de 1881 e discute as passagens em disputa. É a peça central da controvérsia sobre o texto crítico: quem quer avaliá-la deve ler o argumento original, não apenas as críticas a ele.',
    base: 'domínio público',
  },
  {
    id: 'lutero-tres-tratados',
    autor: 'Martinho Lutero',
    ano: '1520',
    titulo: 'First Principles of the Reformation: as 95 teses e os três tratados primários',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/firstprinciples00buchgoog',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03', 'TP01', 'TS11', 'TS06'],
    nota: 'Reúne À Nobreza Cristã da Nação Alemã, O Cativeiro Babilônico e A Liberdade Cristã — os três escritos de 1520 em que a Reforma expõe seu programa. Traz o argumento do sacerdócio de todos os crentes, que demoliu a divisão entre estado espiritual e temporal. A biblioteca não tinha nenhuma obra de Lutero.',
    base: 'domínio público',
  },
  {
    id: 'lutero-catecismo',
    autor: 'Martinho Lutero',
    ano: '1529',
    titulo: 'The Small Catechism of Dr. Martin Luther',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/smallcatechismof00luth',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP10', 'TS11', 'TS53', 'TH03'],
    nota: 'O catecismo que inaugurou o gênero na Reforma. Vale ler o prefácio antes do conteúdo: nele Lutero relata a visita às paróquias da Saxônia em 1528, onde encontrou gente que não sabia o Pai-Nosso, e explica que escreveu aquilo por necessidade. É o documento de fundação da educação cristã protestante.',
    base: 'domínio público',
  },
  {
    id: 'watts-logick',
    autor: 'Isaac Watts',
    ano: '1724',
    titulo: 'Logick: or, The Right Use of Reason in the Enquiry after Truth',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/logickorrightuse00wattuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG58', 'CG06', 'TS51', 'TE16'],
    nota: 'O manual de lógica escrito por um pastor — o mesmo autor de centenas de hinos — e adotado como livro-texto em universidades inglesas e americanas por mais de um século. Trata explicitamente do uso da razão nos assuntos de religião, o que o torna a introdução mais adequada para este currículo.',
    base: 'domínio público',
  },
  {
    id: 'charles-enoque',
    autor: 'R. H. Charles (trad.)',
    ano: '1912',
    titulo: 'The Book of Enoch, or 1 Enoch',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/bookofenochor1en00char',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE55', 'TE51', 'TE02', 'TS07'],
    nota: 'A apocalipse judaica não canônica mais importante do período intertestamentário, em tradução do próprio editor do texto etíope. Permite ao estudante ver o gênero apocalíptico em ação fora do cânon e comparar por conta própria — em vez de aceitar a descrição de um manual sobre um texto que ele nunca leu.',
    base: 'domínio público',
  },
  {
    id: 'catecismo-maior',
    autor: 'Assembleia de Westminster',
    ano: '1647',
    titulo: 'O Catecismo Maior de Westminster',
    publicacao: 'Monergismo',
    url: 'https://www.monergismo.com/textos/catecismos/catecismomaior_westminster.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS11', 'TS53', 'TS10', 'TP10', 'TS01', 'TS04'],
    nota: 'As 196 perguntas e respostas em português, em texto corrido e sem paywall. Completa o par com o Breve Catecismo: onde este resume, o Maior desdobra — e a exposição dos Dez Mandamentos, nas perguntas 91 a 152, é o tratamento mais detalhado da lei moral que a tradição reformada produziu em forma catequética, o que o torna material de ética cristã tanto quanto de doutrina.',
    base: 'domínio público',
  },
  {
    id: 'heidelberg',
    autor: 'Zacarias Ursino e Gaspar Oleviano',
    ano: '1563',
    titulo: 'Catecismo de Heidelberg',
    publicacao: 'Monergismo',
    url: 'https://www.monergismo.com/textos/catecismos/catecismo_heidelberg.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS53', 'TS11', 'TP10', 'TS04', 'TS10'],
    nota: 'O catecismo mais afetuoso da tradição reformada, organizado em miséria, redenção e gratidão, e dividido em 52 domingos para ser pregado ao longo do ano. Abre perguntando qual é o seu único consolo na vida e na morte — e a diferença de tom em relação a Westminster é ela mesma uma lição sobre como se ensina doutrina.',
    base: 'domínio público',
  },
  {
    id: 'confissao-belga',
    autor: 'Guido de Bräs',
    ano: '1561',
    titulo: 'Confissão Belga',
    publicacao: 'Monergismo',
    url: 'https://www.monergismo.com/textos/credos/confissao_belga.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS53', 'TS11', 'TS01', 'TS06'],
    nota: 'A confissão das igrejas reformadas do continente, escrita por um pastor que seria executado por sua fé quatro anos depois. Foi redigida para mostrar às autoridades que os reformados não eram sediciosos — o que explica seu tom e a atenção que dá à relação entre igreja e Estado.',
    base: 'domínio público',
  },
  {
    id: 'helvetica-2',
    autor: 'Heinrich Bullinger',
    ano: '1566',
    titulo: 'Segunda Confissão Helvética',
    publicacao: 'Monergismo',
    url: 'https://www.monergismo.com/textos/credos/seg-confissao-helvetica.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TS53', 'TS11', 'TS08', 'TS09', 'TS06'],
    nota: 'Escrita pelo sucessor de Zuínglio em Zurique e adotada por igrejas reformadas de vários países, o que a torna o documento de maior alcance internacional da primeira geração. A afirmação de que a pregação da Palavra de Deus é a Palavra de Deus está aqui, e é uma das frases mais citadas sobre o ofício do pregador.',
    base: 'domínio público',
  },
  {
    id: 'watts-improvement',
    autor: 'Isaac Watts',
    ano: '1741',
    titulo: 'The Improvement of the Mind: or, a Supplement to the Art of Logick',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/suppimproveofmin00wattuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG06', 'CG12', 'CG13', 'CG58', 'TE16'],
    nota: 'Tratado sobre como estudar, ler, tomar notas, conversar e escrever, do mesmo pastor que escreveu a Logick. É o clássico protestante de método intelectual e trata de coisas que os manuais atuais de metodologia raramente abordam — como ler um livro com que se discorda, ou como conversar de modo que a conversa ensine alguma coisa.',
    base: 'domínio público',
  },
  {
    id: 'tylor-primitive',
    autor: 'Edward Burnett Tylor',
    ano: '1871',
    titulo: 'Primitive Culture: Researches into the Development of Mythology, Philosophy, Religion, Art and Custom',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/primitiveculture01tylouoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG11', 'CG62', 'TP27', 'TS51', 'TP25'],
    nota: 'A obra que fundou a antropologia da religião e propôs a escada animismo–politeísmo–monoteísmo. Leia como fonte primária de uma hipótese que a própria disciplina depois abandonou, não como descrição confiável dos povos que trata. Traz a definição de cultura mais citada do século XIX.',
    base: 'domínio público',
  },
  {
    id: 'frazer-golden-bough',
    autor: 'James George Frazer',
    ano: '1890',
    titulo: 'The Golden Bough: A Study in Comparative Religion',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/cu31924021569128',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG11', 'CG62', 'TS51', 'TE51'],
    nota: 'Popularizou a sequência magia–religião–ciência e influenciou gerações muito além da antropologia. Vale pelo método — comparar práticas de contextos radicalmente distintos como variantes de um mesmo tipo —, que é exatamente o procedimento que o trabalho de campo posterior desautorizou.',
    base: 'domínio público',
  },
  {
    id: 'james-principles',
    autor: 'William James',
    ano: '1890',
    titulo: 'The Principles of Psychology, vol. I',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/PrinciplesOfPsychologyVol1',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG07', 'CG62', 'CG64', 'CG08'],
    nota: 'O tratado que estabeleceu a psicologia como disciplina no mundo de língua inglesa, escrito por alguém que ainda argumentava como filósofo — e por isso trata explicitamente das questões que a psicologia posterior passou a pressupor sem discutir, como a natureza do eu, do hábito e da vontade.',
    base: 'domínio público',
  },
  {
    id: 'james-varieties',
    autor: 'William James',
    ano: '1902',
    titulo: 'The Varieties of Religious Experience',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/varietiesofrelig00jameuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG62', 'CG07', 'CG11', 'TS51'],
    nota: 'As conferências Gifford que fundaram a psicologia da religião. Examina conversões, misticismo e santidade com simpatia e sem reduzi-los a patologia — mas avaliando-os pelos frutos, o que é ao mesmo tempo o mérito e o limite da obra para uma leitura reformada. É a fonte primária de CG62 inteira.',
    base: 'domínio público',
  },
  {
    id: 'broadus-sermoes',
    autor: 'John A. Broadus',
    ano: '1870',
    titulo: 'A Treatise on the Preparation and Delivery of Sermons',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/treatiseonprepar00broarich',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP14', 'TP15', 'TP16', 'TP17', 'TP18', 'TP19', 'TP58', 'CG60'],
    nota: 'O manual de homilética mais influente da língua inglesa, usado como livro-texto por mais de um século. Trata de assunto, arranjo, estilo e entrega com um detalhamento que os manuais atuais raramente alcançam, e serve às cinco disciplinas de Prática de Pregação além da Homilética.',
    base: 'domínio público',
  },
  {
    id: 'nevius-igrejas',
    autor: 'John Livingston Nevius',
    ano: '1886',
    titulo: 'The Planting and Development of Missionary Churches',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/plantingdevelopm00nevi',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP25', 'TP20', 'TP07', 'TP08', 'TP26'],
    nota: 'Opúsculo curto que descreve o método das três autonomias em operação, escrito por quem o aplicava na China e o viu prosperar na Coreia. Substitui com vantagem os resumos de segunda mão: o argumento contra assalariar convertidos com dinheiro da missão está aqui em primeira pessoa, com os casos que o motivaram.',
    base: 'domínio público',
  },
  {
    id: 'taylor-retrospect',
    autor: 'James Hudson Taylor',
    ano: '1894',
    titulo: 'A Retrospect',
    publicacao: 'Project Gutenberg',
    url: 'https://www.gutenberg.org/ebooks/26744',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP25', 'TP07', 'TP08', 'TP27', 'TH04'],
    nota: 'Narrativa em primeira pessoa do fundador da Missão ao Interior da China. É a fonte primária do exemplo mais citado de adaptação de forma sem cessão de conteúdo — adotar traje e costumes chineses, contra a opinião dos colegas — e mostra o custo pessoal da decisão, que os resumos costumam omitir.',
    base: 'domínio público',
  },
  {
    id: 'apmt-ipb',
    autor: 'Igreja Presbiteriana do Brasil',
    ano: 's.d.',
    titulo: 'Agência Presbiteriana de Missões Transculturais',
    publicacao: 'IPB',
    url: 'https://www.ipb.org.br/autarquias-apmt.php',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP25', 'TP07', 'TP08', 'TP60'],
    nota: 'A autarquia pela qual a IPB envia e sustenta obreiros transculturais. Não é obra de estudo, e sim o endereço institucional em que a discussão se torna prática para quem pretende ir: em que campos a denominação já está e por onde passa o envio.',
    base: 'edição autorizada',
  },
  {
    id: 'fairbairn-hermeneutica',
    autor: 'Patrick Fairbairn',
    ano: '1858',
    titulo: 'Hermeneutical Manual: Introduction to the Exegetical Study of the Scriptures of the New Testament',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/hermeneuticalma00fair',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE16', 'TE13', 'TE12', 'TE20', 'TE21', 'TE22'],
    nota: 'O livro-texto reformado desta disciplina que existe em domínio público, escrito por um professor da Free Church of Scotland. Trata o estudo exegético do Novo Testamento passo a passo e dedica extensão incomum ao uso do Antigo Testamento pelos apóstolos — o ponto exato em que se decide quanto do sentido o autor humano precisava conhecer.',
    base: 'domínio público',
  },
  {
    id: 'terry-hermeneutica',
    autor: 'Milton Spenser Terry',
    ano: '1883',
    titulo: 'Biblical Hermeneutics: A Treatise on the Interpretation of the Old and New Testaments',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/biblicalhermeneu00terr',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE16', 'TE12', 'TE13', 'TE17', 'TE20', 'TE55'],
    nota: 'O tratado mais completo de hermenêutica em domínio público, padrão da disciplina por quase um século: análise gramatical, contexto histórico, tipos, profecia e gêneros, com exemplos trabalhados. Terry é metodista e diverge do padrão reformado em escatologia e no tratamento dos tipos — leia a metodologia com proveito e essas partes comparando com Fairbairn.',
    base: 'domínio público',
  },
  {
    id: 'watts-hinos',
    autor: 'Isaac Watts',
    ano: '1707',
    titulo: 'Hymns and Spiritual Songs, in Three Books',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/hymnsspiritusupp00watt',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG59', 'TS08', 'TS09', 'TH04'],
    nota: 'A coleção que fundou o hino inglês moderno. O prefácio é a peça decisiva: Watts justifica ali por que compôs letra humana para o culto, e recebeu por isso a acusação de corromper a adoração — o mesmo argumento que hoje se usa contra quem compõe. Domínio público.',
    base: 'domínio público',
  },
  {
    id: 'julian-hinologia',
    autor: 'John Julian',
    ano: '1892',
    titulo: 'A Dictionary of Hymnology, vol. I',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/dictionaryofhymn01lond',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG59', 'TS08', 'TH04'],
    nota: 'A obra de referência da hinologia: origem, autoria, data e história de uso de milhares de hinos. Substitui com folga qualquer manual em catálogo para a pergunta que mais rende nesta disciplina — de onde veio, de fato, o que a igreja considera imemorial. Domínio público.',
    base: 'domínio público',
  },
  {
    id: 'monergismo-culto',
    autor: 'Vários',
    ano: '—',
    titulo: 'A Teologia do Culto Reformado',
    publicacao: 'Monergismo',
    url: 'https://www.monergismo.com/textos/adoracao/teologia_culto.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG59', 'TS08', 'TS09'],
    nota: 'Material em português sobre adoração e culto reformado, útil a quem precisa levar a discussão a um conselho que não lê inglês. Já era citado pelo verbete do princípio regulador sem constar do acervo.',
    base: 'edição autorizada',
  },
  {
    id: 'juliano-cartas',
    autor: 'Juliano, imperador romano',
    ano: '362',
    titulo: 'The Works of the Emperor Julian, vol. III — Letters',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/worksofemperorj03juli',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP52', 'TH01', 'TH02', 'CG08'],
    nota: 'O volume das cartas, em grego e inglês em páginas opostas. A Carta a Arsácio, de 362, é a peça mais citada: o imperador que tentava restaurar o paganismo instrui um sacerdote a copiar a caridade cristã, porque não conseguia competir com ela. Testemunho hostil sobre a igreja antiga — vale mais que uma apologia.',
    base: 'domínio público',
  },
  {
    id: 'chalmers-economia-civica',
    autor: 'Thomas Chalmers',
    ano: '1821',
    titulo: 'The Christian and Civic Economy of Large Towns, vol. I',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/christianandciv01chalgoog',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP52', 'TP06', 'TP26', 'TH03'],
    nota: 'O relato de Chalmers sobre a paróquia de St. John\'s, em Glasgow, com os números que o sustentam: como a divisão em quarteirões pequenos, cada um sob um diácono que conhecia as famílias, reduziu o gasto e melhorou o resultado. É a obra que os manuais contemporâneos de diaconia citam de segunda mão. Domínio público.',
    base: 'domínio público',
  },
  {
    id: 'rauschenbusch-crise-social',
    autor: 'Walter Rauschenbusch',
    ano: '1907',
    titulo: 'Christianity and the Social Crisis',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/christianitysoci00rausiala',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP52', 'TS10', 'TH03', 'CG13'],
    nota: 'A obra que fundou o evangelho social, na voz do autor e não na caricatura. Entra aqui como fonte a ser lida criticamente: o diagnóstico das condições sociais é forte, e é justamente por isso que a substituição da categoria de Reino se torna visível. Quem só conhece a refutação nunca viu o argumento.',
    base: 'domínio público',
  },
  {
    id: 'ipb-cas',
    autor: 'Igreja Presbiteriana do Brasil',
    ano: '—',
    titulo: 'Conselho de Ação Social (CAS/IPB)',
    publicacao: 'Igreja Presbiteriana do Brasil',
    url: 'https://www.ipb.org.br/conselho-acao-social',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP52', 'TP06', 'TP13'],
    nota: 'As competências regimentais do CAS no site oficial da denominação: registro das instituições sociais da igreja, coordenação de socorro em catástrofes regionais e auxílio a ministros jubilados e viúvas necessitadas. É a camada institucional que a ementa de Ação Social cobra e que nenhum manual estrangeiro cobre.',
    base: 'edição autorizada',
  },
  {
    id: 'smith-geografia',
    autor: 'George Adam Smith',
    ano: '1894',
    titulo: 'The Historical Geography of the Holy Land',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/historicalgeogra00smit',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE03', 'TE51', 'TE18', 'TE20'],
    nota: 'A obra que fundou a geografia histórica bíblica em língua inglesa e segue citada mais de um século depois. Smith percorreu a região a pé e descreve o que viu — é livro de leitura, não de consulta, e substitui com folga o manual de geografia bíblica que se compraria.',
    base: 'domínio público',
  },
  {
    id: 'smith-atlas',
    autor: 'George Adam Smith',
    ano: '1915',
    titulo: 'Atlas of the Historical Geography of the Holy Land',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/atlasofhistorica00smit',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE03', 'TE51', 'TE20', 'TH01'],
    nota: 'O volume de mapas que acompanha a geografia histórica: relevo, regime de chuvas, rotas comerciais e os mapas políticos por período. Cobre o essencial do que se procura num atlas bíblico de catálogo, e está inteiro em domínio público.',
    base: 'domínio público',
  },
  {
    id: 'luckenbill-assiria-2',
    autor: 'Daniel David Luckenbill',
    ano: '1927',
    titulo: 'Ancient Records of Assyria and Babylonia, vol. II',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/LuckenbillAncientRecordsAssyria02',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE03', 'TE51', 'TE18', 'TE19'],
    nota: 'As inscrições reais assírias de Sargão em diante, traduzidas e numeradas, inclusive os anais de Senaqueribe com a campanha de 701 contra Judá. É de onde os manuais tiram a citação do "pássaro na gaiola" — aqui no contexto inteiro, que é onde o argumento realmente está.',
    base: 'domínio público',
  },
  {
    id: 'breasted-egito-3',
    autor: 'James Henry Breasted',
    ano: '1906',
    titulo: 'Ancient Records of Egypt, vol. III — The Nineteenth Dynasty',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/ancientrecordsof03brea_0',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE03', 'TE51', 'TE18'],
    nota: 'Os documentos egípcios da XIX dinastia, com a estela de Merneptá e a menção mais antiga a Israel fora da Bíblia. Breasted anota os sinais determinativos, o que permite ver por que se lê ali um povo e não um território.',
    base: 'domínio público',
  },
  {
    id: 'barton-arqueologia',
    autor: 'George A. Barton',
    ano: '1916',
    titulo: 'Archaeology and the Bible',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/archaeologybible00bartuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE03', 'TE51', 'TE18', 'TE19'],
    nota: 'Manual em duas partes: a primeira percorre as terras bíblicas e a história das escavações, a segunda traz traduzidos os documentos do Oriente Próximo que iluminam o texto. A datação de sítios envelheceu e a parte I pede reservas; a antologia da parte II segue útil, e é justamente o que falta a quem estuda em português.',
    base: 'domínio público',
  },
  {
    id: 'josefo-obras',
    autor: 'Flávio Josefo',
    ano: '93',
    titulo: 'The Works of Flavius Josephus (trad. William Whiston)',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/workstranslatedb00joseuoft',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TE03', 'TE51', 'TH01', 'TE02', 'TE20'],
    nota: 'As Antiguidades e a Guerra dos Judeus na tradução clássica de Whiston. A descrição de Jerusalém e do templo em Guerra V é a fonte antiga mais detalhada sobre a cidade no tempo de Cristo, escrita por quem a viu antes da destruição — lendo-se com a ressalva de que Josefo escreve para romanos e tem interesse no próprio lado.',
    base: 'domínio público',
  },
  {
    id: 'ibge-urbanizacao',
    autor: 'Instituto Brasileiro de Geografia e Estatística',
    ano: '2023',
    titulo: 'Censo Demográfico 2022: população e domicílios — primeiros resultados',
    publicacao: 'Biblioteca do IBGE',
    url: 'https://biblioteca.ibge.gov.br/visualizacao/livros/liv102011.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP26', 'TP52', 'CG13', 'TP20'],
    nota: 'O volume oficial dos primeiros resultados do Censo 2022, com as tabelas de população por situação urbana e rural — o dado da inversão demográfica brasileira em fonte primária. O mesmo levantamento desce ao setor censitário no portal do IBGE, o que permite a conta que todo conselho deveria fazer: quantas pessoas moram no raio de um quilômetro da igreja.',
    base: 'edição autorizada',
  },
  {
    id: 'mearns-outcast-london',
    autor: 'Andrew Mearns',
    ano: '1883',
    titulo: 'The Bitter Cry of Outcast London',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/bittercryofoutca00lond',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP26', 'TP52', 'TH03'],
    nota: 'Panfleto curto que sacudiu as igrejas de Londres ao descrever o que havia nos cortiços a poucos minutos de suas portas. Vale menos pelo argumento e mais pelo método: descreve cômodos, não médias. É o modelo do que se deve levantar sobre o próprio bairro antes de planejar qualquer trabalho.',
    base: 'domínio público',
  },
  {
    id: 'booth-darkest-england',
    autor: 'William Booth',
    ano: '1890',
    titulo: 'In Darkest England and the Way Out',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/indarkestenglan00bootgoog',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP26', 'TP52', 'TP20'],
    nota: 'O plano urbano do fundador do Exército de Salvação: diagnóstico e execução, com colônias, oficinas, abrigos e agência de emprego. Discorde da eclesiologia à vontade — o que se ganha aqui é ver um projeto de missão urbana desenhado até o nível do orçamento, coisa que a literatura devocional sobre cidade nunca faz.',
    base: 'domínio público',
  },
  {
    id: 'strong-cidade',
    autor: 'Josiah Strong',
    ano: '1898',
    titulo: 'The Twentieth Century City',
    publicacao: 'Internet Archive',
    url: 'https://archive.org/details/twentiethcentur00strogoog',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP26', 'TP52', 'CG13'],
    nota: 'Texto fundador da missiologia urbana protestante e, ao mesmo tempo, advertência sobre como ela descarrila: a preocupação legítima de Strong com a cidade vem misturada a teses de superioridade anglo-saxã que hoje se leem com constrangimento. Entra pelas duas razões, e a segunda é a mais instrutiva.',
    base: 'domínio público',
  },
];

export const porDisciplina = (codigo: string) =>
  biblioteca.filter((o) => o.disciplinas.includes(codigo));
