import type { ObraLivre } from './biblioteca';

/**
 * Fontes abertas acrescentadas nos ciclos de aprofundamento editorial.
 *
 * O arquivo começa pequeno de propósito: ele evita inflar os arquivos históricos
 * da biblioteca e oferece um ponto estável para novas fontes que sejam realmente
 * necessárias ao aprofundamento, sem transformar contagem de obras em meta.
 */
export const bibliotecaAprofundamento: ObraLivre[] = [
  {
    id: 'openstax-psychology-2e',
    autor: 'Rose M. Spielman; William J. Jenkins; Marilyn D. Lovett',
    ano: '2020',
    titulo: 'Psychology 2e',
    publicacao: 'OpenStax, Rice University',
    url: 'https://openstax.org/books/psychology-2e/pages/1-introduction',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TP04', 'CG07'],
    nota: 'Livro-texto universitário aberto usado para caracterizar, em fonte acadêmica acessível, as contribuições e os limites históricos de Freud, Skinner, Jung, Maslow e Rogers. Serve ao portal como referência descritiva, não como norma antropológica ou teológica.',
    base: 'edição autorizada',
  },
  {
    id: 'codigo-civil-br',
    autor: 'Brasil',
    ano: '2002',
    titulo: 'Código Civil — Lei 10.406/2002, texto compilado',
    publicacao: 'Presidência da República',
    url: 'https://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP06', 'CG55'],
    nota: 'Fonte oficial para personalidade jurídica das organizações religiosas, representação, contratos, propriedade e casamento religioso com efeitos civis. É a referência legal primária para distinguir regras denominacionais internas dos efeitos civis produzidos fora da igreja.',
    base: 'edição autorizada',
  },
  {
    id: 'lei-registros-publicos',
    autor: 'Brasil',
    ano: '1973',
    titulo: 'Lei 6.015/1973 — Registros Públicos, texto compilado',
    publicacao: 'Presidência da República',
    url: 'https://www.planalto.gov.br/ccivil_03/leis/l6015compilada.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP06'],
    nota: 'Fonte oficial para registro de imóveis e para o registro do casamento religioso com efeitos civis. Permite ensinar as rotinas documentais sem depender de formulários locais ou de instruções desatualizadas.',
    base: 'edição autorizada',
  },
  {
    id: 'ipb-forcas-integracao-2024',
    autor: 'Igreja Presbiteriana do Brasil',
    ano: '2024',
    titulo: 'Sociedades internas, federações e confederações sinodais — Brasil Presbiteriano, agosto de 2024',
    publicacao: 'Igreja Presbiteriana do Brasil',
    url: 'https://www.ipb.org.br/content/conteudos/65cf180f-b9bb-4fd1-b345-16e067f2e8c4_BP-837-agosto-2024-3.pdf',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP06'],
    nota: 'Artigo institucional que descreve a estrutura vigente das forças de integração: sociedades internas locais, federações presbiteriais, confederações sinodais e confederações nacionais, relacionando-as à Constituição da IPB e ao GTSI.',
    base: 'edição autorizada',
  },
  {
    id: 'receita-ministro-confissao-130-2021',
    autor: 'Receita Federal do Brasil',
    ano: '2021',
    titulo: 'Solução de Consulta Cosit 130/2021 — Ministro de confissão religiosa',
    publicacao: 'Receita Federal do Brasil',
    url: 'https://normas.receita.fazenda.gov.br/sijut2consulta/consulta.action?termoBusca=971%252F09',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TP06'],
    nota: 'Orientação oficial sobre a condição previdenciária do ministro como contribuinte individual e sobre incidência de imposto de renda. É usada para atualizar o tratamento curricular de INSS e IR sem transformar resumo pastoral em consultoria tributária individual.',
    base: 'edição autorizada',
  },
  {
    id: 'camara-constituicao-1824',
    autor: 'Brasil',
    ano: '1824',
    titulo: 'Constituição Política do Império do Brasil — publicação original',
    publicacao: 'Câmara dos Deputados',
    url: 'https://www2.camara.leg.br/legin/fed/consti/1824-1899/constituicao-35041-25-marco-1824-532540-publicacaooriginal-14770-pl.html',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'CG65'],
    nota: 'Texto oficial da Constituição de 1824. O artigo 5 estabelece o catolicismo como religião do Império e restringe o culto público das demais religiões; o documento permite estudar Igreja e Estado no período imperial a partir da norma primária, não de uma paráfrase posterior.',
    base: 'domínio público',
  },
  {
    id: 'planalto-decreto-119a-1890',
    autor: 'Brasil',
    ano: '1890',
    titulo: 'Decreto 119-A, de 7 de janeiro de 1890 — liberdade de cultos e extinção do padroado',
    publicacao: 'Presidência da República',
    url: 'https://www.planalto.gov.br/ccivil_03/decreto/1851-1899/d119-a.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'CG65'],
    nota: 'Fonte legal primária da separação republicana entre Igreja e Estado. O decreto proíbe o estabelecimento estatal de religião, garante o exercício coletivo dos cultos e extingue expressamente o padroado.',
    base: 'domínio público',
  },
  {
    id: 'scielo-pombal-2006',
    autor: 'Lizete Shizue Bomura Maciel; Alexandre Shigunov Neto',
    ano: '2006',
    titulo: 'A educação brasileira no período pombalino: uma análise histórica das reformas pombalinas do ensino',
    publicacao: 'Educação e Pesquisa / SciELO',
    url: 'https://www.scielo.br/j/ep/a/7bgbrBdvs3tHHHFg36c6Z9B/?lang=pt',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'CG09'],
    nota: 'Artigo acadêmico aberto sobre a reforma pombalina, a expulsão dos jesuítas em 1759 e a transferência de funções educacionais para a Coroa. É útil para evitar tanto a celebração automática de Pombal como secularizador quanto a narrativa de simples destruição sem contexto político.',
    base: 'edição autorizada',
  },
  {
    id: 'scielo-inquisicao-brasil-2008',
    autor: 'Aldair Carlos Rodrigues',
    ano: '2008',
    titulo: 'Formação e atuação da rede de comissários do Santo Ofício em Minas colonial',
    publicacao: 'Revista Brasileira de História / SciELO',
    url: 'https://www.scielo.br/j/rbh/a/z46NyTR4ztZ8VfnRw3yBNLd/?lang=pt',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05'],
    nota: 'Pesquisa histórica aberta que mostra como o Brasil permaneceu sob a jurisdição da Inquisição de Lisboa sem possuir tribunal próprio, sendo alcançado por visitações, justiça eclesiástica e redes de comissários e familiares.',
    base: 'edição autorizada',
  },
  {
    id: 'scielo-ultramontanismo-2017',
    autor: 'Douglas Nassif Cardoso',
    ano: '2017',
    titulo: 'Ultramontanismo e protestantismo no período regencial: uma análise da crítica panfletária à missão metodista no Brasil',
    publicacao: 'Almanack / SciELO',
    url: 'https://www.scielo.br/j/alm/a/7MfBjh5zyXRcDf9sbJLtVqy/abstract/?lang=pt',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05'],
    nota: 'Artigo acadêmico que situa a missão metodista em meio às tensões entre regalismo, ultramontanismo e liberdade religiosa no período regencial. Ajuda a ler a chegada protestante sem projetar sobre o Império a liberdade religiosa posterior.',
    base: 'edição autorizada',
  },
  {
    id: 'loc-kidder-fletcher-1866',
    autor: 'Daniel P. Kidder; James C. Fletcher',
    ano: '1866',
    titulo: 'Brazil and the Brazilians: Portrayed in Historical and Descriptive Sketches',
    publicacao: 'Library of Congress',
    url: 'https://www.loc.gov/item/36004087/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH05', 'CG63'],
    nota: 'Edição digital integral, em domínio público, de uma das principais descrições protestantes do Brasil imperial. Kidder atuou na missão metodista inicial; a obra permite observar diretamente religião, circulação bíblica, costumes e restrições do século XIX.',
    base: 'domínio público',
  },
  {
    id: 'scielo-pentecostalismo-mariano-2004',
    autor: 'Ricardo Mariano',
    ano: '2004',
    titulo: 'Expansão pentecostal no Brasil: o caso da Igreja Universal',
    publicacao: 'Estudos Avançados / SciELO',
    url: 'https://www.scielo.br/j/ea/a/H6DCFyvKr6Yrxw7W6pWJcBz/?format=html&lang=pt',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'CG10'],
    nota: 'Estudo acadêmico aberto que apresenta a periodização clássica do pentecostalismo brasileiro, distingue Congregação Cristã e Assembleia de Deus das ondas posteriores e analisa a institucionalização neopentecostal sem tratar todo o campo evangélico como bloco homogêneo.',
    base: 'edição autorizada',
  },
  {
    id: 'scielo-messianismo-giumbelli-1997',
    autor: 'Emerson Giumbelli',
    ano: '1997',
    titulo: 'Religião e (Des)Ordem Social: Contestado, Juazeiro e Canudos nos Estudos Sociológicos sobre Movimentos Religiosos',
    publicacao: 'Dados / SciELO',
    url: 'https://www.scielo.br/j/dados/a/LYmsT7Y9grnCy5xRQn9fwyQ/?lang=pt',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH05', 'CG10'],
    nota: 'Revisão crítica da literatura sobre Canudos, Contestado e Juazeiro. É especialmente útil para evitar que a categoria “messianismo” substitua a análise das relações entre catolicismo popular, coronelismo, classe e conflito social.',
    base: 'edição autorizada',
  },
];
