import type { ObraLivre } from './biblioteca';

/**
 * Fontes abertas acrescentadas na reta final de cobertura das disciplinas
 * sistemáticas eletivas. Mantidas separadas para que cada inclusão permaneça
 * pequena, auditável e fácil de retirar/substituir se um acervo mudar.
 */
export const bibliotecaFinal: ObraLivre[] = [
  {
    id: 'schaff-creeds-2',
    autor: 'Philip Schaff',
    ano: '1877',
    titulo: 'The Creeds of Christendom, vol. II — Greek and Latin Creeds',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://ccel.org/ccel/schaff/creeds2/creeds2.toc.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS53', 'TH01', 'TH02'],
    nota: 'Reúne regras de fé antigas, Credo Apostólico, Niceia-Constantinopla, Calcedônia e outros símbolos em textos comparáveis. É a fonte aberta mais útil para acompanhar a formação dos credos ecumênicos sem depender de citações de segunda mão.',
    base: 'domínio público',
  },
  {
    id: 'orange-529',
    autor: 'Segundo Concílio de Orange',
    ano: '529',
    titulo: 'Canons of the Second Council of Orange, A.D. 529',
    publicacao: 'Open Library — edição de 1882',
    url: 'https://openlibrary.org/books/OL28397248M/Canons_of_the_Second_Council_of_Orange_A.D._529',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS53', 'TH02', 'TS04'],
    nota: 'Edição histórica em latim e inglês dos cânones sobre graça, pecado e livre-arbítrio. Permite situar Orange como testemunho ocidental anterior à Reforma sem projetar retrospectivamente sobre o concílio todo o sistema reformado posterior.',
    base: 'domínio público',
  },
  {
    id: 'wrf-statement-2011',
    autor: 'World Reformed Fellowship',
    ano: '2011',
    titulo: 'World Reformed Fellowship Statement of Faith',
    publicacao: 'World Reformed Fellowship',
    url: 'https://wrfnet.org/about/statement-of-faith',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS53'],
    nota: 'Página oficial da declaração concluída em 2011. A própria WRF explica que pretende expressar elementos comuns das confissões reformadas históricas, aplicar a fé a questões do século XXI e incluir vozes reformadas globais, sem substituir os símbolos históricos.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-postmodernism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2015',
    titulo: 'Postmodernism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/postmodernism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS54', 'CG65'],
    nota: 'Verbete acadêmico usado para distinguir pós-modernismo de caricaturas populares, situar Lyotard, Foucault, Derrida e seus precursores e mostrar a diversidade interna das correntes associadas ao rótulo.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-relativism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2020',
    titulo: 'Relativism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/relativism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS54', 'CG08', 'CG65'],
    nota: 'Panorama revisado por especialistas das diferentes famílias de relativismo. Ajuda a separar relativismo epistêmico, moral e outras formas da simples constatação de diversidade cultural ou da finitude do conhecedor.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-critical-theory',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2023',
    titulo: 'Critical Theory (Frankfurt School)',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/critical-theory/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS54', 'CG65'],
    nota: 'Verbete contemporâneo sobre a Escola de Frankfurt e os sentidos estrito e amplo de teoria crítica. Serve para distinguir tradições marxistas reais de usos totalizantes e conspiratórios da expressão “marxismo cultural”.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-religious-pluralism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2025',
    titulo: 'Religious Diversity (Pluralism)',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/religious-pluralism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TS54'],
    nota: 'Panorama acadêmico atualizado sobre diversidade religiosa, exclusivismo, pluralismo, desacordo e tolerância. É especialmente útil para não confundir o fato sociológico da diversidade com uma tese filosófica sobre a verdade ou eficácia salvífica de religiões incompatíveis.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-atheism-agnosticism',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '2022',
    titulo: 'Atheism and Agnosticism',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/atheism-agnosticism/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TS51', 'CG65'],
    nota: 'Distingue usos psicológicos, metafísicos e epistemológicos de ateísmo e agnosticismo. Evita que a apologética responda a uma definição diferente daquela que o interlocutor realmente sustenta.',
    base: 'edição autorizada',
  },
  {
    id: 'pickthall-koran-1930',
    autor: 'Muhammad Marmaduke Pickthall, trad.',
    ano: '1930',
    titulo: 'The Meaning of the Glorious Koran',
    publicacao: 'Wikisource',
    url: 'https://en.wikisource.org/wiki/The_Meaning_of_the_Glorious_Koran_(1930)',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TP56'],
    nota: 'Tradução inglesa produzida por um muçulmano. A edição de 1930 está em domínio público nos Estados Unidos desde 2026 e oferece acesso primário ao texto corânico; não substitui a diversidade da tradição interpretativa islâmica.',
    base: 'domínio público',
  },
  {
    id: 'gita-swarupananda-1909',
    autor: 'Swami Swarupananda, trad. e coment.',
    ano: '1909',
    titulo: 'Srimad-Bhagavad-Gita',
    publicacao: 'Internet Sacred Text Archive',
    url: 'https://archive.sacred-texts.com/hin/sbg/sbg00.htm',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TP56'],
    nota: 'Tradução e comentário hindu em domínio público. Permite observar ação, conhecimento, devoção, karma e libertação numa fonte da própria tradição, em vez de reduzir o hinduísmo a um slogan apologético.',
    base: 'domínio público',
  },
  {
    id: 'dhammapada-1920',
    autor: 'W. D. C. Wagiswara e K. J. Saunders, trads.',
    ano: '1920',
    titulo: "The Buddha's Way of Virtue — A Translation of the Dhammapada",
    publicacao: 'Internet Sacred Text Archive',
    url: 'https://www.sacred-texts.com/bud/wov/wov00.htm',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TS55', 'TP56'],
    nota: 'Tradução do Dhammapada em domínio público. É uma porta de entrada textual para desejo, conduta, mente e libertação, sem pretender representar sozinha Theravāda, Mahāyāna, Vajrayāna e demais tradições budistas.',
    base: 'domínio público',
  },
  {
    id: 'crcna-canons-dort',
    autor: 'Sínodo de Dort',
    ano: '1619',
    titulo: 'The Canons of Dort',
    publicacao: 'Christian Reformed Church in North America',
    url: 'https://www.crcna.org/welcome/beliefs/confessions/canons-dort',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03', 'TS04', 'TS11', 'TS53'],
    nota: 'Texto integral em edição eclesiástica autorizada, com introdução, artigos positivos e rejeições de erros. É a referência primária preferencial para conferir estrutura e formulação dos Cânones.',
    base: 'edição autorizada',
  },
  {
    id: 'schaff-creeds-history-dort',
    autor: 'Philip Schaff',
    ano: '1877',
    titulo: 'The Arminian Controversy and the Synod of Dort, A.D. 1604–1619',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/schaff/creeds1.ix.iii.iv.html',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH03', 'TS04', 'TS11', 'TS53'],
    nota: 'Introdução histórica em domínio público sobre a controvérsia arminiana, o caráter internacional do sínodo e a recepção dos Cânones.',
    base: 'domínio público',
  },
  {
    id: 'monergismo-canones-dort',
    autor: 'Sínodo de Dort',
    ano: '1619',
    titulo: 'Os Cânones de Dort',
    publicacao: 'Monergismo',
    url: 'https://www.monergismo.com/textos/credos/dort.htm',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['TH03', 'TS04', 'TS11', 'TS53'],
    nota: 'Tradução portuguesa integral, aberta e estável, que permite ao estudante brasileiro ler diretamente a decisão sinodal.',
    base: 'edição autorizada',
  },
];
