import type { ObraLivre } from './biblioteca';

/**
 * Entradas recuperadas pela auditoria de integridade de 19/08/2026 e novas
 * fontes abertas incorporadas após a consolidação inicial do acervo.
 *
 * Ficam separadas do arquivo histórico apenas para que as correções sejam
 * pequenas e auditáveis. `biblioteca-completa.ts` é a fonte consumida pela
 * interface e pelos validadores.
 */
export const bibliotecaExtra: ObraLivre[] = [
  {
    id: 'sep-faith',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Faith',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/faith/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08'],
    nota: 'Verbete acadêmico revisado por especialistas sobre os conceitos de fé e sua relação com razão, evidência e conhecimento.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-filosofia-religiao',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Philosophy of Religion',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/philosophy-religion/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG08'],
    nota: 'Panorama acadêmico aberto dos principais problemas da filosofia da religião e das relações entre fé, razão e linguagem religiosa.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-enlightenment',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Enlightenment',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/enlightenment/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG65'],
    nota: 'Síntese acadêmica aberta do Iluminismo, útil para situar a mudança epistemológica que molda a filosofia moderna.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-hume',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'David Hume',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/hume/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG65'],
    nota: 'Verbete acadêmico aberto sobre Hume, incluindo causalidade, conhecimento e crítica da religião.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-kant',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Immanuel Kant',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/kant/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG65'],
    nota: 'Introdução acadêmica aberta ao projeto crítico de Kant, à epistemologia e aos limites impostos à metafísica.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-nietzsche',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Friedrich Nietzsche',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/nietzsche/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG65'],
    nota: 'Verbete acadêmico aberto sobre a crítica nietzschiana da moral, da religião e das pretensões de verdade.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-plato',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Plato',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/plato/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG09'],
    nota: 'Introdução acadêmica aberta à filosofia de Platão e a seus principais problemas metafísicos, epistemológicos e éticos.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-aquinas',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Thomas Aquinas',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/aquinas/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG09'],
    nota: 'Verbete acadêmico aberto sobre Tomás de Aquino, incluindo metafísica, conhecimento e a relação entre filosofia e teologia.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-fallacies',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Fallacies',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/fallacies/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG58'],
    nota: 'Tratamento acadêmico aberto da história e classificação das falácias, com atenção às dificuldades de defini-las apenas por listas de erros.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-aristotle-logic',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: "Aristotle's Logic",
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/aristotle-logic/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG58'],
    nota: 'Introdução acadêmica aberta à lógica aristotélica, ao silogismo e à tradição formal que dele se desenvolveu.',
    base: 'edição autorizada',
  },
  {
    id: 'sep-weber',
    autor: 'Stanford Encyclopedia of Philosophy',
    ano: '—',
    titulo: 'Max Weber',
    publicacao: 'Stanford University',
    url: 'https://plato.stanford.edu/entries/weber/',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['CG10'],
    nota: 'Verbete acadêmico aberto sobre Weber, racionalização, ação social, religião e modernidade.',
    base: 'edição autorizada',
  },
  {
    id: 'schaff-hcc2-pdf',
    autor: 'Philip Schaff',
    ano: '1885',
    titulo: 'History of the Christian Church, vol. II — PDF integral',
    publicacao: 'Christian Classics Ethereal Library',
    url: 'https://www.ccel.org/ccel/s/schaff/hcc2/cache/hcc2.pdf',
    idioma: 'en',
    acesso: 'livre',
    disciplinas: ['TH01'],
    nota: 'O segundo volume de Schaff em arquivo único, útil para leitura offline e citação; a mesma obra também está disponível em HTML.',
    base: 'domínio público',
  },
  {
    id: 'pm4ngos-project-dpro',
    autor: 'PM4NGOs',
    ano: '2020',
    titulo: 'Guia Project DPro — PMD Pro, 2ª edição',
    publicacao: 'PM4NGOs',
    url: 'https://pm4ngos.org/pt-br/metodologias-e-guias/project-dpro-pmd-pro/',
    idioma: 'pt',
    acesso: 'livre',
    disciplinas: ['CG53', 'TP60'],
    nota: 'Guia gratuito em português para gerenciamento de projetos no setor de desenvolvimento, com ferramentas de desenho, planejamento, execução, monitoramento, encerramento e sustentabilidade. A própria PM4NGOs o distribui sob licença Creative Commons BY-NC 4.0.',
    base: 'edição autorizada',
  },
];
